[2025-02-01T21:31:42.107+0000] {processor.py:186} INFO - Started process (PID=40) to work on /opt/airflow/dags/test.py
[2025-02-01T21:31:42.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:31:42.119+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:31:42.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:31:43.309+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:31:43.300+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:31:43.313+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:31:43.345+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:31:43.345+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:31:43.367+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:31:43.366+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:31:43.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.317 seconds
[2025-02-01T21:32:13.570+0000] {processor.py:186} INFO - Started process (PID=52) to work on /opt/airflow/dags/test.py
[2025-02-01T21:32:13.572+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:32:13.574+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:32:13.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:32:13.737+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:32:13.736+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:32:13.739+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:32:13.765+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:32:13.765+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:32:13.783+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:32:13.783+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:32:13.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.371 seconds
[2025-02-01T21:32:44.339+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/test.py
[2025-02-01T21:32:44.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:32:44.342+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:32:44.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:32:44.520+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:32:44.519+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:32:44.522+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:32:44.545+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:32:44.545+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:32:44.689+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:32:44.689+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:32:44.704+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.369 seconds
[2025-02-01T21:33:14.868+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/test.py
[2025-02-01T21:33:14.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:33:14.870+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:33:14.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:33:15.034+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:33:15.033+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:33:15.036+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:33:15.192+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:33:15.191+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:33:15.202+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:33:15.202+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:33:15.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.355 seconds
[2025-02-01T21:33:45.747+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/test.py
[2025-02-01T21:33:45.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:33:45.750+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:33:45.750+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:33:45.916+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:33:45.915+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:33:45.918+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:33:46.069+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:33:46.069+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:33:46.080+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:33:46.080+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:33:46.094+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.352 seconds
[2025-02-01T21:34:16.231+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/test.py
[2025-02-01T21:34:16.236+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:34:16.238+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:34:16.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:34:16.535+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:34:16.535+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:34:16.537+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:34:16.556+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:34:16.556+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:34:16.567+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:34:16.567+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:34:16.582+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.355 seconds
[2025-02-01T21:34:46.633+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/test.py
[2025-02-01T21:34:46.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:34:46.636+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:34:46.636+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:34:46.951+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:34:46.950+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:34:46.952+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:34:46.973+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:34:46.973+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:34:46.989+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:34:46.988+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:34:47.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.380 seconds
[2025-02-01T21:35:17.330+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/test.py
[2025-02-01T21:35:17.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:35:17.333+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:35:17.332+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:35:17.505+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:35:17.505+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:35:17.507+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:35:17.529+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:35:17.529+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:35:17.548+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:35:17.548+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:35:17.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.242 seconds
[2025-02-01T21:35:47.615+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/test.py
[2025-02-01T21:35:47.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:35:47.618+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:35:47.617+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:35:47.783+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:35:47.782+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:35:47.785+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:35:47.814+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:35:47.813+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:35:47.831+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:35:47.831+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:35:47.851+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.240 seconds
[2025-02-01T21:36:17.885+0000] {processor.py:186} INFO - Started process (PID=143) to work on /opt/airflow/dags/test.py
[2025-02-01T21:36:17.886+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:36:17.887+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:36:17.887+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:36:18.052+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:36:18.051+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:36:18.054+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:36:18.078+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:36:18.077+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:36:18.091+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:36:18.090+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:36:18.107+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.227 seconds
[2025-02-01T21:36:48.309+0000] {processor.py:186} INFO - Started process (PID=155) to work on /opt/airflow/dags/test.py
[2025-02-01T21:36:48.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:36:48.311+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:36:48.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:36:48.475+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:36:48.474+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:36:48.477+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:36:48.498+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:36:48.498+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:36:48.510+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:36:48.510+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:36:48.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.221 seconds
[2025-02-01T21:37:18.684+0000] {processor.py:186} INFO - Started process (PID=167) to work on /opt/airflow/dags/test.py
[2025-02-01T21:37:18.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:37:18.687+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:37:18.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:37:18.857+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:37:18.856+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:37:18.859+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:37:18.882+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:37:18.882+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:37:18.896+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:37:18.895+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:37:18.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.233 seconds
[2025-02-01T21:37:49.697+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/test.py
[2025-02-01T21:37:49.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:37:49.700+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:37:49.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:37:49.869+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:37:49.868+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:37:49.872+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:37:49.900+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:37:49.899+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:37:49.917+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:37:49.917+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:37:49.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.241 seconds
[2025-02-01T21:38:20.585+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/test.py
[2025-02-01T21:38:20.586+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:38:20.589+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:38:20.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:38:20.866+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:38:20.865+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:38:20.868+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:38:20.895+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:38:20.895+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:38:20.911+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:38:20.911+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:38:20.929+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.351 seconds
[2025-02-01T21:38:51.589+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/test.py
[2025-02-01T21:38:51.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:38:51.592+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:38:51.592+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:38:51.880+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:38:51.879+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:38:51.882+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:38:51.903+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:38:51.903+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:38:51.915+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:38:51.915+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:38:51.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.348 seconds
[2025-02-01T21:39:22.119+0000] {processor.py:186} INFO - Started process (PID=216) to work on /opt/airflow/dags/test.py
[2025-02-01T21:39:22.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:39:22.121+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:39:22.121+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:39:22.285+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:39:22.284+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:39:22.287+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:39:22.315+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:39:22.315+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:39:22.332+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:39:22.332+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:39:22.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.239 seconds
[2025-02-01T21:39:52.513+0000] {processor.py:186} INFO - Started process (PID=228) to work on /opt/airflow/dags/test.py
[2025-02-01T21:39:52.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:39:52.515+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:39:52.515+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:39:52.682+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:39:52.681+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:39:52.685+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:39:52.712+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:39:52.712+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:39:52.731+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:39:52.730+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:39:52.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.240 seconds
[2025-02-01T21:40:23.554+0000] {processor.py:186} INFO - Started process (PID=240) to work on /opt/airflow/dags/test.py
[2025-02-01T21:40:23.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:40:23.558+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:40:23.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:40:23.723+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:40:23.722+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:40:23.726+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:40:23.755+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:40:23.755+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:40:23.769+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:40:23.768+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:40:23.785+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.237 seconds
[2025-02-01T21:40:54.493+0000] {processor.py:186} INFO - Started process (PID=252) to work on /opt/airflow/dags/test.py
[2025-02-01T21:40:54.494+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:40:54.495+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:40:54.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:40:54.682+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:40:54.681+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:40:54.684+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:40:54.707+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:40:54.707+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:40:54.720+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:40:54.720+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:40:54.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.247 seconds
[2025-02-01T21:41:25.357+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/test.py
[2025-02-01T21:41:25.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:41:25.360+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:41:25.359+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:41:25.523+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:41:25.522+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:41:25.525+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:41:25.553+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:41:25.552+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:41:25.569+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:41:25.569+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:41:25.587+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.235 seconds
[2025-02-01T21:41:56.242+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/test.py
[2025-02-01T21:41:56.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:41:56.244+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:41:56.244+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:41:56.409+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:41:56.408+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:41:56.412+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:41:56.439+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:41:56.439+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:41:56.455+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:41:56.455+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:41:56.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.237 seconds
[2025-02-01T21:42:27.127+0000] {processor.py:186} INFO - Started process (PID=288) to work on /opt/airflow/dags/test.py
[2025-02-01T21:42:27.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:42:27.129+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:42:27.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:42:27.292+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:42:27.291+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:42:27.294+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:42:27.321+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:42:27.321+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:42:27.338+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:42:27.338+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:42:27.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.233 seconds
[2025-02-01T21:42:57.901+0000] {processor.py:186} INFO - Started process (PID=300) to work on /opt/airflow/dags/test.py
[2025-02-01T21:42:57.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:42:57.904+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:42:57.904+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:42:58.072+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:42:58.071+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:42:58.073+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:42:58.095+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:42:58.094+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:42:58.106+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:42:58.106+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:42:58.121+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.225 seconds
[2025-02-01T21:43:28.218+0000] {processor.py:186} INFO - Started process (PID=312) to work on /opt/airflow/dags/test.py
[2025-02-01T21:43:28.219+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:43:28.221+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:43:28.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:43:28.387+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:43:28.386+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:43:28.390+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:43:28.416+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:43:28.416+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:43:28.433+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:43:28.433+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:43:28.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.238 seconds
[2025-02-01T21:43:59.099+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/test.py
[2025-02-01T21:43:59.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:43:59.102+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:43:59.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:43:59.283+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:43:59.282+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:43:59.286+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:43:59.308+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:43:59.308+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:43:59.320+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:43:59.320+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:43:59.336+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.242 seconds
[2025-02-01T21:44:29.988+0000] {processor.py:186} INFO - Started process (PID=336) to work on /opt/airflow/dags/test.py
[2025-02-01T21:44:29.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:44:29.991+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:44:29.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:44:30.162+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:44:30.161+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:44:30.164+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:44:30.191+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:44:30.190+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:44:30.207+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:44:30.206+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:44:30.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.243 seconds
[2025-02-01T21:45:00.857+0000] {processor.py:186} INFO - Started process (PID=348) to work on /opt/airflow/dags/test.py
[2025-02-01T21:45:00.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:45:00.859+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:45:00.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:45:01.028+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:45:01.027+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:45:01.030+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:45:01.052+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:45:01.052+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:45:01.066+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:45:01.065+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:45:01.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.229 seconds
[2025-02-01T21:45:31.627+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/test.py
[2025-02-01T21:45:31.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:45:31.630+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:45:31.630+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:45:31.795+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:45:31.794+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:45:31.797+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:45:31.825+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:45:31.824+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:45:31.841+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:45:31.840+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:45:31.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.236 seconds
[2025-02-01T21:46:02.023+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/test.py
[2025-02-01T21:46:02.024+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:46:02.026+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:46:02.026+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:46:02.330+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:46:02.328+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:46:02.332+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:46:02.362+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:46:02.361+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:46:02.380+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:46:02.380+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:46:02.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.381 seconds
[2025-02-01T21:46:33.022+0000] {processor.py:186} INFO - Started process (PID=385) to work on /opt/airflow/dags/test.py
[2025-02-01T21:46:33.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:46:33.025+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:46:33.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:46:33.193+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:46:33.191+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:46:33.195+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:46:33.223+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:46:33.223+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:46:33.240+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:46:33.239+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:46:33.258+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.241 seconds
[2025-02-01T21:47:03.917+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/test.py
[2025-02-01T21:47:03.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:47:03.921+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:47:03.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:47:04.208+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:47:04.206+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:47:04.210+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:47:04.238+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:47:04.237+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:47:04.255+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:47:04.254+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:47:04.277+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.366 seconds
[2025-02-01T21:47:34.437+0000] {processor.py:186} INFO - Started process (PID=409) to work on /opt/airflow/dags/test.py
[2025-02-01T21:47:34.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:47:34.440+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:47:34.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:47:34.601+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:47:34.600+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:47:34.603+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:47:34.624+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:47:34.624+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:47:34.637+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:47:34.637+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:47:34.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.220 seconds
[2025-02-01T21:48:04.696+0000] {processor.py:186} INFO - Started process (PID=421) to work on /opt/airflow/dags/test.py
[2025-02-01T21:48:04.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:48:04.699+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:48:04.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:48:04.861+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:48:04.861+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:48:04.863+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:48:04.891+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:48:04.891+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:48:04.909+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:48:04.908+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:48:04.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.236 seconds
[2025-02-01T21:53:00.998+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/test.py
[2025-02-01T21:53:00.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:53:01.001+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:53:01.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:53:01.297+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:53:01.293+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:53:01.300+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:53:01.340+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:53:01.340+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:53:01.360+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:53:01.359+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:53:01.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.412 seconds
[2025-02-01T21:53:31.980+0000] {processor.py:186} INFO - Started process (PID=47) to work on /opt/airflow/dags/test.py
[2025-02-01T21:53:31.981+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:53:31.983+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:53:31.983+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:53:32.150+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:53:32.149+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:53:32.152+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:53:32.176+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:53:32.176+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:53:32.188+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:53:32.188+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:53:32.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.229 seconds
[2025-02-01T21:54:03.060+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/test.py
[2025-02-01T21:54:03.061+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:54:03.064+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:54:03.064+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:54:03.365+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:54:03.363+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:54:03.367+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:54:03.397+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:54:03.397+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:54:03.580+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:54:03.579+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:54:03.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.546 seconds
[2025-02-01T21:54:34.545+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/test.py
[2025-02-01T21:54:34.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:54:34.547+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:54:34.547+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:54:34.710+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:54:34.709+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:54:34.712+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:54:34.736+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:54:34.735+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:54:34.875+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:54:34.875+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:54:34.888+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.348 seconds
[2025-02-01T21:55:05.737+0000] {processor.py:186} INFO - Started process (PID=90) to work on /opt/airflow/dags/test.py
[2025-02-01T21:55:05.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:55:05.740+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:55:05.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:55:05.904+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:55:05.903+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:55:05.906+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:55:06.055+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:55:06.055+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:55:06.066+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:55:06.066+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:55:06.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.347 seconds
[2025-02-01T21:55:36.990+0000] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/test.py
[2025-02-01T21:55:36.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:55:36.992+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:55:36.992+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:55:37.280+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:55:37.279+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:55:37.281+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:55:37.298+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:55:37.298+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:55:37.309+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:55:37.309+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:55:37.322+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.336 seconds
[2025-02-01T21:56:08.082+0000] {processor.py:186} INFO - Started process (PID=114) to work on /opt/airflow/dags/test.py
[2025-02-01T21:56:08.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:56:08.089+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:56:08.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:56:08.378+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:56:08.377+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:56:08.379+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:56:08.397+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:56:08.397+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:56:08.407+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:56:08.407+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:56:08.421+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.344 seconds
[2025-02-01T21:56:39.107+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/test.py
[2025-02-01T21:56:39.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:56:39.109+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:56:39.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:56:39.278+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:56:39.277+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:56:39.280+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:56:39.305+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:56:39.305+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:56:39.321+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:56:39.321+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:56:39.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.232 seconds
[2025-02-01T21:57:10.141+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/test.py
[2025-02-01T21:57:10.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:57:10.144+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:57:10.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:57:10.308+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:57:10.307+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:57:10.310+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:57:10.332+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:57:10.331+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:57:10.344+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:57:10.343+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:57:10.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.222 seconds
[2025-02-01T21:57:41.112+0000] {processor.py:186} INFO - Started process (PID=150) to work on /opt/airflow/dags/test.py
[2025-02-01T21:57:41.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:57:41.114+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:57:41.114+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:57:41.277+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:57:41.276+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:57:41.280+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:57:41.299+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:57:41.299+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:57:41.311+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:57:41.311+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:57:41.325+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.218 seconds
[2025-02-01T21:58:12.061+0000] {processor.py:186} INFO - Started process (PID=162) to work on /opt/airflow/dags/test.py
[2025-02-01T21:58:12.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:58:12.064+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:58:12.064+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:58:12.231+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:58:12.231+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:58:12.233+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:58:12.254+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:58:12.254+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:58:12.266+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:58:12.266+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:58:12.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.223 seconds
[2025-02-01T21:58:43.021+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/test.py
[2025-02-01T21:58:43.022+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T21:58:43.023+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:58:43.023+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T21:58:43.191+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:58:43.190+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T21:58:43.193+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T21:58:43.213+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:58:43.213+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T21:58:43.225+0000] {logging_mixin.py:190} INFO - [2025-02-01T21:58:43.225+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T21:58:43.242+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.225 seconds
[2025-02-01T22:10:51.829+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/test.py
[2025-02-01T22:10:51.831+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:10:51.835+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:10:51.834+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:10:52.098+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:10:52.088+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:10:52.100+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:10:52.145+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:10:52.145+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:10:52.171+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:10:52.170+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:10:52.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.369 seconds
[2025-02-01T22:11:22.909+0000] {processor.py:186} INFO - Started process (PID=48) to work on /opt/airflow/dags/test.py
[2025-02-01T22:11:22.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:11:22.911+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:11:22.911+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:11:23.080+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:11:23.080+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:11:23.082+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:11:23.102+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:11:23.102+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:11:23.114+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:11:23.113+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:11:23.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.225 seconds
[2025-02-01T22:11:53.872+0000] {processor.py:186} INFO - Started process (PID=60) to work on /opt/airflow/dags/test.py
[2025-02-01T22:11:53.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:11:53.875+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:11:53.874+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:11:54.041+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:11:54.040+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:11:54.043+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:11:54.067+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:11:54.067+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:11:54.195+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:11:54.194+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:11:54.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.342 seconds
[2025-02-01T22:12:25.022+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/test.py
[2025-02-01T22:12:25.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:12:25.025+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:12:25.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:12:25.219+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:12:25.218+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:12:25.221+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:12:25.243+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:12:25.242+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:12:25.385+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:12:25.385+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:12:25.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.381 seconds
[2025-02-01T22:12:56.173+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/test.py
[2025-02-01T22:12:56.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:12:56.176+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:12:56.175+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:12:56.349+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:12:56.349+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:12:56.351+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:12:56.506+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:12:56.506+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:12:56.517+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:12:56.517+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:12:56.531+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.363 seconds
[2025-02-01T22:13:27.450+0000] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/test.py
[2025-02-01T22:13:27.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:13:27.453+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:13:27.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:13:27.746+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:13:27.745+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:13:27.747+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:13:27.765+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:13:27.764+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:13:27.775+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:13:27.775+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:13:27.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.344 seconds
[2025-02-01T22:13:58.568+0000] {processor.py:186} INFO - Started process (PID=114) to work on /opt/airflow/dags/test.py
[2025-02-01T22:13:58.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:13:58.571+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:13:58.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:13:58.885+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:13:58.884+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:13:58.886+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:13:58.904+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:13:58.904+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:13:58.914+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:13:58.914+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:13:58.929+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.365 seconds
[2025-02-01T22:14:29.633+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/test.py
[2025-02-01T22:14:29.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:14:29.635+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:14:29.635+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:14:29.803+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:14:29.802+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:14:29.806+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:14:29.829+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:14:29.829+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:14:29.843+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:14:29.843+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:14:29.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.230 seconds
[2025-02-01T22:15:00.660+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/test.py
[2025-02-01T22:15:00.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:15:00.663+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:15:00.662+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:15:00.848+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:15:00.847+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:15:00.850+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:15:00.871+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:15:00.870+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:15:00.883+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:15:00.882+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:15:00.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.242 seconds
[2025-02-01T22:15:31.669+0000] {processor.py:186} INFO - Started process (PID=150) to work on /opt/airflow/dags/test.py
[2025-02-01T22:15:31.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:15:31.671+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:15:31.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:15:31.837+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:15:31.836+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:15:31.839+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:15:31.859+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:15:31.859+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:15:31.871+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:15:31.871+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:15:31.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.221 seconds
[2025-02-01T22:16:02.856+0000] {processor.py:186} INFO - Started process (PID=162) to work on /opt/airflow/dags/test.py
[2025-02-01T22:16:02.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:16:02.861+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:16:02.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:16:03.053+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:16:03.052+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:16:03.055+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:16:03.083+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:16:03.083+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:16:03.101+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:16:03.101+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:16:03.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.273 seconds
[2025-02-01T22:16:33.986+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/test.py
[2025-02-01T22:16:33.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:16:33.989+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:16:33.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:16:34.155+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:16:34.154+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:16:34.157+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:16:34.177+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:16:34.177+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:16:34.190+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:16:34.189+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:16:34.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.225 seconds
[2025-02-01T22:17:04.810+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/test.py
[2025-02-01T22:17:04.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:17:04.813+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:17:04.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:17:04.991+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:17:04.990+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:17:04.993+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:17:05.013+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:17:05.012+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:17:05.026+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:17:05.025+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:17:05.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.234 seconds
[2025-02-01T22:17:35.711+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/test.py
[2025-02-01T22:17:35.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:17:35.713+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:17:35.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:17:35.877+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:17:35.876+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:17:35.879+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:17:35.900+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:17:35.900+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:17:35.912+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:17:35.912+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:17:35.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.221 seconds
[2025-02-01T22:18:06.835+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/test.py
[2025-02-01T22:18:06.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:18:06.838+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:18:06.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:18:07.002+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:18:07.001+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:18:07.003+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:18:07.024+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:18:07.023+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:18:07.035+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:18:07.035+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:18:07.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.220 seconds
[2025-02-01T22:18:37.984+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/test.py
[2025-02-01T22:18:37.985+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:18:37.987+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:18:37.987+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:18:38.271+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:18:38.270+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:18:38.274+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:18:38.298+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:18:38.298+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:18:38.311+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:18:38.310+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:18:38.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.349 seconds
[2025-02-01T22:19:09.256+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/test.py
[2025-02-01T22:19:09.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:19:09.260+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:19:09.259+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:19:09.444+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:19:09.443+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:19:09.446+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:19:09.467+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:19:09.466+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:19:09.479+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:19:09.478+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:19:09.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.245 seconds
[2025-02-01T22:19:40.583+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/dags/test.py
[2025-02-01T22:19:40.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:19:40.587+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:19:40.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:19:40.862+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:19:40.861+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:19:40.864+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:19:40.884+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:19:40.884+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:19:40.897+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:19:40.897+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:19:40.913+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.336 seconds
[2025-02-01T22:20:11.553+0000] {processor.py:186} INFO - Started process (PID=258) to work on /opt/airflow/dags/test.py
[2025-02-01T22:20:11.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:20:11.557+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:20:11.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:20:11.719+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:20:11.718+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:20:11.721+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:20:11.743+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:20:11.743+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:20:11.756+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:20:11.756+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:20:11.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.225 seconds
[2025-02-01T22:20:42.672+0000] {processor.py:186} INFO - Started process (PID=270) to work on /opt/airflow/dags/test.py
[2025-02-01T22:20:42.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:20:42.675+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:20:42.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:20:42.838+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:20:42.837+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:20:42.839+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:20:42.860+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:20:42.860+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:20:42.872+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:20:42.871+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:20:42.886+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.220 seconds
[2025-02-01T22:21:13.619+0000] {processor.py:186} INFO - Started process (PID=282) to work on /opt/airflow/dags/test.py
[2025-02-01T22:21:13.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:21:13.622+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:21:13.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:21:13.787+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:21:13.786+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:21:13.789+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:21:13.809+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:21:13.809+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:21:13.821+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:21:13.821+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:21:13.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.221 seconds
[2025-02-01T22:21:44.558+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/test.py
[2025-02-01T22:21:44.559+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:21:44.561+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:21:44.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:21:44.728+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:21:44.727+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:21:44.730+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:21:44.750+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:21:44.750+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:21:44.762+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:21:44.762+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:21:44.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.224 seconds
[2025-02-01T22:22:15.442+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/test.py
[2025-02-01T22:22:15.443+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:22:15.445+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:22:15.444+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:22:15.615+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:22:15.614+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:22:15.616+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:22:15.638+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:22:15.638+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:22:15.651+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:22:15.651+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:22:15.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.227 seconds
[2025-02-01T22:22:46.483+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/test.py
[2025-02-01T22:22:46.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:22:46.485+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:22:46.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:22:46.670+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:22:46.669+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:22:46.672+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:22:46.693+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:22:46.693+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:22:46.705+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:22:46.705+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:22:46.719+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.242 seconds
[2025-02-01T22:23:17.430+0000] {processor.py:186} INFO - Started process (PID=330) to work on /opt/airflow/dags/test.py
[2025-02-01T22:23:17.430+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:23:17.432+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:23:17.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:23:17.594+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:23:17.594+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:23:17.596+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:23:17.615+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:23:17.615+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:23:17.627+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:23:17.627+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:23:17.640+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.215 seconds
[2025-02-01T22:23:48.368+0000] {processor.py:186} INFO - Started process (PID=342) to work on /opt/airflow/dags/test.py
[2025-02-01T22:23:48.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:23:48.371+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:23:48.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:23:48.537+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:23:48.536+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:23:48.539+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:23:48.561+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:23:48.561+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:23:48.572+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:23:48.572+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:23:48.586+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.223 seconds
[2025-02-01T22:24:19.681+0000] {processor.py:186} INFO - Started process (PID=354) to work on /opt/airflow/dags/test.py
[2025-02-01T22:24:19.682+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:24:19.683+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:24:19.683+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:24:19.847+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:24:19.846+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:24:19.849+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:24:19.873+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:24:19.873+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:24:19.887+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:24:19.886+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:24:19.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.227 seconds
[2025-02-01T22:24:50.688+0000] {processor.py:186} INFO - Started process (PID=366) to work on /opt/airflow/dags/test.py
[2025-02-01T22:24:50.688+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:24:50.690+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:24:50.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:24:50.852+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:24:50.852+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:24:50.854+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:24:50.875+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:24:50.875+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:24:50.890+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:24:50.890+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:24:50.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.221 seconds
[2025-02-01T22:25:21.617+0000] {processor.py:186} INFO - Started process (PID=378) to work on /opt/airflow/dags/test.py
[2025-02-01T22:25:21.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:25:21.620+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:25:21.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:25:21.786+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:25:21.785+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:25:21.788+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:25:21.810+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:25:21.809+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:25:21.822+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:25:21.822+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:25:21.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.226 seconds
[2025-02-01T22:25:52.603+0000] {processor.py:186} INFO - Started process (PID=390) to work on /opt/airflow/dags/test.py
[2025-02-01T22:25:52.605+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:25:52.606+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:25:52.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:25:52.781+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:25:52.780+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:25:52.783+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:25:52.805+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:25:52.805+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:25:52.818+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:25:52.818+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:25:52.833+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.235 seconds
[2025-02-01T22:26:23.631+0000] {processor.py:186} INFO - Started process (PID=402) to work on /opt/airflow/dags/test.py
[2025-02-01T22:26:23.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:26:23.634+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:26:23.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:26:23.797+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:26:23.796+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:26:23.799+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:26:23.820+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:26:23.819+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:26:23.832+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:26:23.832+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:26:23.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.223 seconds
[2025-02-01T22:26:54.622+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/test.py
[2025-02-01T22:26:54.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:26:54.625+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:26:54.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:26:54.785+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:26:54.784+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:26:54.787+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:26:54.808+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:26:54.807+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:26:54.821+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:26:54.821+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:26:54.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.218 seconds
[2025-02-01T22:27:25.625+0000] {processor.py:186} INFO - Started process (PID=426) to work on /opt/airflow/dags/test.py
[2025-02-01T22:27:25.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:27:25.628+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:27:25.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:27:25.812+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:27:25.812+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:27:25.814+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:27:25.835+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:27:25.835+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:27:25.847+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:27:25.847+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:27:25.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.242 seconds
[2025-02-01T22:27:56.569+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/airflow/dags/test.py
[2025-02-01T22:27:56.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:27:56.572+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:27:56.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:27:56.756+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:27:56.755+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:27:56.758+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:27:56.779+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:27:56.778+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:27:56.791+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:27:56.790+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:27:56.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.241 seconds
[2025-02-01T22:28:27.678+0000] {processor.py:186} INFO - Started process (PID=450) to work on /opt/airflow/dags/test.py
[2025-02-01T22:28:27.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:28:27.681+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:28:27.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:28:27.867+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:28:27.866+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:28:27.869+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:28:27.890+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:28:27.890+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:28:27.902+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:28:27.902+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:28:27.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.245 seconds
[2025-02-01T22:28:58.856+0000] {processor.py:186} INFO - Started process (PID=468) to work on /opt/airflow/dags/test.py
[2025-02-01T22:28:58.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:28:58.859+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:28:58.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:28:59.022+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:28:59.022+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:28:59.024+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:28:59.046+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:28:59.045+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:28:59.058+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:28:59.058+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:28:59.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.223 seconds
[2025-02-01T22:29:29.789+0000] {processor.py:186} INFO - Started process (PID=480) to work on /opt/airflow/dags/test.py
[2025-02-01T22:29:29.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:29:29.792+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:29:29.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:29:29.955+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:29:29.954+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:29:29.956+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:29:29.976+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:29:29.976+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:29:29.989+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:29:29.989+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:29:30.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.219 seconds
[2025-02-01T22:30:00.873+0000] {processor.py:186} INFO - Started process (PID=491) to work on /opt/airflow/dags/test.py
[2025-02-01T22:30:00.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:30:00.876+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:30:00.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:30:01.070+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:30:01.069+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:30:01.072+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:30:01.093+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:30:01.093+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:30:01.107+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:30:01.107+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:30:01.121+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.253 seconds
[2025-02-01T22:30:32.249+0000] {processor.py:186} INFO - Started process (PID=503) to work on /opt/airflow/dags/test.py
[2025-02-01T22:30:32.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:30:32.252+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:30:32.251+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:30:32.422+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:30:32.421+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:30:32.424+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:30:32.451+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:30:32.451+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:30:32.466+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:30:32.466+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:30:32.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.237 seconds
[2025-02-01T22:31:03.342+0000] {processor.py:186} INFO - Started process (PID=516) to work on /opt/airflow/dags/test.py
[2025-02-01T22:31:03.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:31:03.345+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:31:03.345+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:31:03.538+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:31:03.537+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:31:03.540+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:31:03.566+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:31:03.566+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:31:03.578+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:31:03.578+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:31:03.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.256 seconds
[2025-02-01T22:31:34.347+0000] {processor.py:186} INFO - Started process (PID=528) to work on /opt/airflow/dags/test.py
[2025-02-01T22:31:34.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:31:34.351+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:31:34.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:31:34.525+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:31:34.524+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:31:34.527+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:31:34.548+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:31:34.548+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:31:34.560+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:31:34.560+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:31:34.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.237 seconds
[2025-02-01T22:32:05.458+0000] {processor.py:186} INFO - Started process (PID=540) to work on /opt/airflow/dags/test.py
[2025-02-01T22:32:05.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:32:05.462+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:32:05.461+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:32:05.648+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:32:05.648+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:32:05.650+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:32:05.671+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:32:05.671+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:32:05.684+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:32:05.684+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:32:05.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.248 seconds
[2025-02-01T22:32:36.549+0000] {processor.py:186} INFO - Started process (PID=552) to work on /opt/airflow/dags/test.py
[2025-02-01T22:32:36.550+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:32:36.552+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:32:36.552+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:32:36.717+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:32:36.716+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:32:36.718+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:32:36.739+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:32:36.739+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:32:36.751+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:32:36.751+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:32:36.766+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.222 seconds
[2025-02-01T22:33:07.500+0000] {processor.py:186} INFO - Started process (PID=564) to work on /opt/airflow/dags/test.py
[2025-02-01T22:33:07.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:33:07.503+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:33:07.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:33:07.669+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:33:07.668+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:33:07.671+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:33:07.691+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:33:07.691+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:33:07.703+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:33:07.702+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:33:07.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.222 seconds
[2025-02-01T22:33:38.454+0000] {processor.py:186} INFO - Started process (PID=576) to work on /opt/airflow/dags/test.py
[2025-02-01T22:33:38.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:33:38.457+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:33:38.457+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:33:38.621+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:33:38.620+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:33:38.623+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:33:38.644+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:33:38.644+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:33:38.656+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:33:38.656+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:33:38.671+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.222 seconds
[2025-02-01T22:34:09.418+0000] {processor.py:186} INFO - Started process (PID=588) to work on /opt/airflow/dags/test.py
[2025-02-01T22:34:09.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:34:09.421+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:34:09.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:34:09.590+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:34:09.589+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:34:09.592+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:34:09.615+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:34:09.615+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:34:09.628+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:34:09.628+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:34:09.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.230 seconds
[2025-02-01T22:34:40.418+0000] {processor.py:186} INFO - Started process (PID=601) to work on /opt/airflow/dags/test.py
[2025-02-01T22:34:40.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:34:40.421+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:34:40.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:34:40.584+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:34:40.584+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:34:40.586+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:34:40.608+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:34:40.607+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:34:40.621+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:34:40.621+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:34:40.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.222 seconds
[2025-02-01T22:35:11.320+0000] {processor.py:186} INFO - Started process (PID=613) to work on /opt/airflow/dags/test.py
[2025-02-01T22:35:11.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:35:11.322+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:35:11.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:35:11.486+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:35:11.485+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:35:11.487+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:35:11.510+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:35:11.510+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:35:11.522+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:35:11.522+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:35:11.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.221 seconds
[2025-02-01T22:35:42.298+0000] {processor.py:186} INFO - Started process (PID=625) to work on /opt/airflow/dags/test.py
[2025-02-01T22:35:42.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:35:42.301+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:35:42.300+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:35:42.465+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:35:42.464+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:35:42.467+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:35:42.487+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:35:42.487+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:35:42.500+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:35:42.500+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:35:42.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.222 seconds
[2025-02-01T22:36:13.421+0000] {processor.py:186} INFO - Started process (PID=637) to work on /opt/airflow/dags/test.py
[2025-02-01T22:36:13.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:36:13.423+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:36:13.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:36:13.596+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:36:13.595+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:36:13.598+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:36:13.618+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:36:13.618+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:36:13.630+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:36:13.630+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:36:13.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.229 seconds
[2025-02-01T22:36:44.461+0000] {processor.py:186} INFO - Started process (PID=650) to work on /opt/airflow/dags/test.py
[2025-02-01T22:36:44.462+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:36:44.464+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:36:44.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:36:44.641+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:36:44.641+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:36:44.643+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:36:44.664+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:36:44.663+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:36:44.677+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:36:44.677+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:36:44.691+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.235 seconds
[2025-02-01T22:37:15.457+0000] {processor.py:186} INFO - Started process (PID=662) to work on /opt/airflow/dags/test.py
[2025-02-01T22:37:15.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:37:15.459+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:37:15.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:37:15.619+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:37:15.618+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:37:15.621+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:37:15.641+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:37:15.641+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:37:15.653+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:37:15.653+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:37:15.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.215 seconds
[2025-02-01T22:37:46.347+0000] {processor.py:186} INFO - Started process (PID=674) to work on /opt/airflow/dags/test.py
[2025-02-01T22:37:46.349+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:37:46.351+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:37:46.351+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:37:46.579+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:37:46.578+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:37:46.581+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:37:46.607+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:37:46.607+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:37:46.623+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:37:46.623+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:37:46.639+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.298 seconds
[2025-02-01T22:38:17.767+0000] {processor.py:186} INFO - Started process (PID=686) to work on /opt/airflow/dags/test.py
[2025-02-01T22:38:17.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:38:17.770+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:38:17.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:38:17.955+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:38:17.954+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:38:17.957+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:38:17.977+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:38:17.977+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:38:17.989+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:38:17.989+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:38:18.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.243 seconds
[2025-02-01T22:38:49.395+0000] {processor.py:186} INFO - Started process (PID=698) to work on /opt/airflow/dags/test.py
[2025-02-01T22:38:49.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:38:49.404+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:38:49.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:38:49.724+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:38:49.722+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:38:49.736+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:38:49.770+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:38:49.770+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:38:49.789+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:38:49.789+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:38:49.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.424 seconds
[2025-02-01T22:39:20.440+0000] {processor.py:186} INFO - Started process (PID=710) to work on /opt/airflow/dags/test.py
[2025-02-01T22:39:20.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:39:20.443+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:39:20.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:39:20.601+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:39:20.601+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:39:20.603+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:39:20.623+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:39:20.623+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:39:20.636+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:39:20.636+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:39:20.649+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.214 seconds
[2025-02-01T22:39:51.018+0000] {processor.py:186} INFO - Started process (PID=721) to work on /opt/airflow/dags/test.py
[2025-02-01T22:39:51.019+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:39:51.021+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:39:51.021+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:39:51.223+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:39:51.222+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:39:51.226+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:39:51.250+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:39:51.250+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:39:51.263+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:39:51.263+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:39:51.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.270 seconds
[2025-02-01T22:40:21.868+0000] {processor.py:186} INFO - Started process (PID=732) to work on /opt/airflow/dags/test.py
[2025-02-01T22:40:21.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:40:21.870+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:40:21.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:40:22.030+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:40:22.029+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:40:22.032+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:40:22.053+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:40:22.053+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:40:22.065+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:40:22.065+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:40:22.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.216 seconds
[2025-02-01T22:40:52.131+0000] {processor.py:186} INFO - Started process (PID=744) to work on /opt/airflow/dags/test.py
[2025-02-01T22:40:52.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:40:52.134+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:40:52.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:40:52.293+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:40:52.292+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:40:52.295+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:40:52.316+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:40:52.316+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:40:52.328+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:40:52.328+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:40:52.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.216 seconds
[2025-02-01T22:41:22.863+0000] {processor.py:186} INFO - Started process (PID=756) to work on /opt/airflow/dags/test.py
[2025-02-01T22:41:22.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:41:22.865+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:41:22.865+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:41:23.029+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:41:23.028+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:41:23.031+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:41:23.051+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:41:23.051+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:41:23.063+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:41:23.063+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:41:23.078+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.220 seconds
[2025-02-01T22:41:53.149+0000] {processor.py:186} INFO - Started process (PID=768) to work on /opt/airflow/dags/test.py
[2025-02-01T22:41:53.150+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:41:53.152+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:41:53.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:41:53.314+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:41:53.314+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:41:53.316+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:41:53.339+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:41:53.338+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:41:53.354+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:41:53.354+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:41:53.368+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.224 seconds
[2025-02-01T22:42:23.753+0000] {processor.py:186} INFO - Started process (PID=780) to work on /opt/airflow/dags/test.py
[2025-02-01T22:42:23.754+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:42:23.756+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:42:23.756+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:42:23.917+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:42:23.916+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:42:23.919+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:42:23.941+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:42:23.941+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:42:23.954+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:42:23.954+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:42:23.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.220 seconds
[2025-02-01T22:42:54.118+0000] {processor.py:186} INFO - Started process (PID=792) to work on /opt/airflow/dags/test.py
[2025-02-01T22:42:54.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:42:54.121+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:42:54.121+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:42:54.282+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:42:54.281+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:42:54.283+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:42:54.304+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:42:54.304+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:42:54.316+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:42:54.316+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:42:54.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.218 seconds
[2025-02-01T22:43:25.133+0000] {processor.py:186} INFO - Started process (PID=803) to work on /opt/airflow/dags/test.py
[2025-02-01T22:43:25.134+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:43:25.136+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:43:25.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:43:25.296+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:43:25.295+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:43:25.298+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:43:25.319+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:43:25.319+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:43:25.331+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:43:25.331+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:43:25.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.219 seconds
[2025-02-01T22:43:55.890+0000] {processor.py:186} INFO - Started process (PID=815) to work on /opt/airflow/dags/test.py
[2025-02-01T22:43:55.891+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:43:55.892+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:43:55.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:43:56.057+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:43:56.056+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:43:56.059+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:43:56.080+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:43:56.080+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:43:56.093+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:43:56.093+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:43:56.111+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.226 seconds
[2025-02-01T22:44:26.273+0000] {processor.py:186} INFO - Started process (PID=826) to work on /opt/airflow/dags/test.py
[2025-02-01T22:44:26.273+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:44:26.275+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:44:26.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:44:26.436+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:44:26.435+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:44:26.438+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:44:26.460+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:44:26.459+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:44:26.473+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:44:26.472+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:44:26.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.220 seconds
[2025-02-01T22:44:57.107+0000] {processor.py:186} INFO - Started process (PID=839) to work on /opt/airflow/dags/test.py
[2025-02-01T22:44:57.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-02-01T22:44:57.110+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:44:57.110+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-02-01T22:44:57.271+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:44:57.270+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-02-01T22:44:57.273+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-02-01T22:44:57.301+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:44:57.301+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-01T22:44:57.318+0000] {logging_mixin.py:190} INFO - [2025-02-01T22:44:57.318+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-02-01T22:44:57.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.235 seconds
