[2025-01-30T19:12:28.009+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/test.py
[2025-01-30T19:12:28.010+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:12:28.012+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:12:28.012+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:12:28.302+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:12:28.300+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:12:28.304+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:12:28.330+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:12:28.330+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:12:28.350+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:12:28.350+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:12:28.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.375 seconds
[2025-01-30T19:12:59.116+0000] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/test.py
[2025-01-30T19:12:59.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:12:59.118+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:12:59.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:12:59.296+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:12:59.295+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:12:59.298+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:12:59.319+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:12:59.318+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:12:59.332+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:12:59.332+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:12:59.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.238 seconds
[2025-01-30T19:13:30.198+0000] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/test.py
[2025-01-30T19:13:30.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:13:30.202+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:13:30.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:13:30.401+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:13:30.400+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:13:30.404+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:13:30.425+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:13:30.425+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:13:30.570+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:13:30.569+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:13:30.585+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.392 seconds
[2025-01-30T19:14:01.419+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/test.py
[2025-01-30T19:14:01.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:14:01.422+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:14:01.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:14:01.708+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:14:01.707+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:14:01.712+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:14:01.744+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:14:01.743+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:14:01.902+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:14:01.901+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:14:01.917+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.504 seconds
[2025-01-30T19:14:32.777+0000] {processor.py:186} INFO - Started process (PID=89) to work on /opt/airflow/dags/test.py
[2025-01-30T19:14:32.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:14:32.781+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:14:32.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:14:32.953+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:14:32.952+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:14:32.955+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:14:33.108+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:14:33.108+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:14:33.119+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:14:33.119+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:14:33.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.361 seconds
[2025-01-30T19:15:04.098+0000] {processor.py:186} INFO - Started process (PID=101) to work on /opt/airflow/dags/test.py
[2025-01-30T19:15:04.099+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:15:04.100+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:15:04.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:15:04.403+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:15:04.402+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:15:04.405+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:15:04.424+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:15:04.424+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:15:04.435+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:15:04.435+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:15:04.450+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.356 seconds
[2025-01-30T19:15:35.275+0000] {processor.py:186} INFO - Started process (PID=113) to work on /opt/airflow/dags/test.py
[2025-01-30T19:15:35.279+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:15:35.281+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:15:35.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:15:35.587+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:15:35.586+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:15:35.589+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:15:35.607+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:15:35.607+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:15:35.618+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:15:35.618+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:15:35.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.363 seconds
[2025-01-30T19:16:06.804+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/test.py
[2025-01-30T19:16:06.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:16:06.807+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:16:06.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:16:07.139+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:16:07.138+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:16:07.142+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:16:07.178+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:16:07.177+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:16:07.204+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:16:07.204+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:16:07.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.429 seconds
[2025-01-30T19:16:38.094+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/test.py
[2025-01-30T19:16:38.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:16:38.098+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:16:38.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:16:38.311+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:16:38.310+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:16:38.313+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:16:38.334+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:16:38.334+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:16:38.346+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:16:38.346+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:16:38.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.275 seconds
[2025-01-30T19:17:09.122+0000] {processor.py:186} INFO - Started process (PID=149) to work on /opt/airflow/dags/test.py
[2025-01-30T19:17:09.123+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:17:09.124+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:17:09.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:17:09.295+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:17:09.294+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:17:09.298+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:17:09.319+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:17:09.318+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:17:09.333+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:17:09.333+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:17:09.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.231 seconds
[2025-01-30T19:17:40.161+0000] {processor.py:186} INFO - Started process (PID=161) to work on /opt/airflow/dags/test.py
[2025-01-30T19:17:40.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:17:40.165+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:17:40.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:17:40.338+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:17:40.337+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:17:40.340+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:17:40.361+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:17:40.361+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:17:40.373+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:17:40.373+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:17:40.389+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.233 seconds
[2025-01-30T19:18:11.247+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/test.py
[2025-01-30T19:18:11.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:18:11.249+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:18:11.249+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:18:11.430+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:18:11.429+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:18:11.432+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:18:11.454+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:18:11.453+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:18:11.466+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:18:11.466+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:18:11.483+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.241 seconds
[2025-01-30T19:18:42.121+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/test.py
[2025-01-30T19:18:42.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:18:42.124+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:18:42.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:18:42.296+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:18:42.295+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:18:42.298+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:18:42.318+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:18:42.318+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:18:42.331+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:18:42.331+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:18:42.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.229 seconds
[2025-01-30T19:19:13.019+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/dags/test.py
[2025-01-30T19:19:13.020+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:19:13.021+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:19:13.021+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:19:13.190+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:19:13.189+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:19:13.192+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:19:13.213+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:19:13.213+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:19:13.225+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:19:13.224+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:19:13.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.224 seconds
[2025-01-30T19:19:44.049+0000] {processor.py:186} INFO - Started process (PID=209) to work on /opt/airflow/dags/test.py
[2025-01-30T19:19:44.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:19:44.052+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:19:44.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:19:44.227+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:19:44.226+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:19:44.229+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:19:44.250+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:19:44.249+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:19:44.262+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:19:44.262+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:19:44.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.234 seconds
[2025-01-30T19:20:15.050+0000] {processor.py:186} INFO - Started process (PID=221) to work on /opt/airflow/dags/test.py
[2025-01-30T19:20:15.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:20:15.053+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:20:15.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:20:15.228+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:20:15.227+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:20:15.230+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:20:15.251+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:20:15.251+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:20:15.263+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:20:15.263+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:20:15.279+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.235 seconds
[2025-01-30T19:20:47.729+0000] {processor.py:186} INFO - Started process (PID=233) to work on /opt/airflow/dags/test.py
[2025-01-30T19:20:47.731+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:20:47.734+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:20:47.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:20:48.060+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:20:48.059+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:20:48.063+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:20:48.093+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:20:48.093+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:20:48.111+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:20:48.111+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:20:48.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.414 seconds
[2025-01-30T19:21:18.280+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/dags/test.py
[2025-01-30T19:21:18.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:21:18.283+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:21:18.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:21:18.508+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:21:18.507+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:21:18.510+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:21:18.532+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:21:18.531+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:21:18.545+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:21:18.545+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:21:18.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.287 seconds
[2025-01-30T19:21:48.675+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/test.py
[2025-01-30T19:21:48.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:21:48.679+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:21:48.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:21:48.854+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:21:48.853+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:21:48.856+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:21:48.885+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:21:48.885+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:21:48.902+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:21:48.901+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:21:48.921+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.251 seconds
[2025-01-30T19:22:19.516+0000] {processor.py:186} INFO - Started process (PID=267) to work on /opt/airflow/dags/test.py
[2025-01-30T19:22:19.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:22:19.520+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:22:19.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:22:19.798+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:22:19.797+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:22:19.800+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:22:19.829+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:22:19.829+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:22:19.847+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:22:19.847+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:22:19.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.357 seconds
[2025-01-30T19:22:49.958+0000] {processor.py:186} INFO - Started process (PID=279) to work on /opt/airflow/dags/test.py
[2025-01-30T19:22:49.959+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:22:49.961+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:22:49.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:22:50.130+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:22:50.129+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:22:50.132+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:22:50.153+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:22:50.153+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:22:50.171+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:22:50.170+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:22:50.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.237 seconds
[2025-01-30T19:23:20.239+0000] {processor.py:186} INFO - Started process (PID=289) to work on /opt/airflow/dags/test.py
[2025-01-30T19:23:20.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:23:20.241+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:23:20.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:23:20.422+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:23:20.421+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:23:20.425+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:23:20.453+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:23:20.453+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:23:20.470+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:23:20.469+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:23:20.494+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.261 seconds
[2025-01-30T19:23:50.743+0000] {processor.py:186} INFO - Started process (PID=301) to work on /opt/airflow/dags/test.py
[2025-01-30T19:23:50.744+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:23:50.746+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:23:50.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:23:50.916+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:23:50.915+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:23:50.918+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:23:50.940+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:23:50.940+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:23:50.953+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:23:50.953+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:23:50.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.231 seconds
[2025-01-30T19:24:21.131+0000] {processor.py:186} INFO - Started process (PID=313) to work on /opt/airflow/dags/test.py
[2025-01-30T19:24:21.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:24:21.134+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:24:21.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:24:21.309+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:24:21.308+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:24:21.311+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:24:21.339+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:24:21.338+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:24:21.354+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:24:21.354+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:24:21.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.245 seconds
[2025-01-30T19:24:52.048+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/test.py
[2025-01-30T19:24:52.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:24:52.051+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:24:52.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:24:52.218+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:24:52.217+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:24:52.220+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:24:52.247+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:24:52.246+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:24:52.263+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:24:52.262+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:24:52.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.237 seconds
[2025-01-30T19:25:22.930+0000] {processor.py:186} INFO - Started process (PID=337) to work on /opt/airflow/dags/test.py
[2025-01-30T19:25:22.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:25:22.932+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:25:22.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:25:23.099+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:25:23.098+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:25:23.101+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:25:23.128+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:25:23.127+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:25:23.141+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:25:23.141+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:25:23.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.234 seconds
[2025-01-30T19:25:53.563+0000] {processor.py:186} INFO - Started process (PID=349) to work on /opt/airflow/dags/test.py
[2025-01-30T19:25:53.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:25:53.566+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:25:53.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:25:53.738+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:25:53.738+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:25:53.740+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:25:53.769+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:25:53.768+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:25:53.785+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:25:53.785+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:25:53.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.245 seconds
[2025-01-30T19:26:23.956+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/test.py
[2025-01-30T19:26:23.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:26:23.959+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:26:23.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:26:24.128+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:26:24.127+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:26:24.130+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:26:24.150+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:26:24.150+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:26:24.163+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:26:24.163+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:26:24.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.228 seconds
[2025-01-30T19:26:54.725+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/test.py
[2025-01-30T19:26:54.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:26:54.727+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:26:54.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:26:54.908+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:26:54.907+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:26:54.909+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:26:54.938+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:26:54.937+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:26:54.954+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:26:54.954+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:26:54.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.253 seconds
[2025-01-30T19:27:25.146+0000] {processor.py:186} INFO - Started process (PID=385) to work on /opt/airflow/dags/test.py
[2025-01-30T19:27:25.148+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:27:25.150+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:27:25.150+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:27:25.319+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:27:25.318+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:27:25.322+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:27:25.351+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:27:25.351+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:27:25.364+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:27:25.364+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:27:25.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.242 seconds
[2025-01-30T19:27:56.041+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/test.py
[2025-01-30T19:27:56.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:27:56.044+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:27:56.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:27:56.213+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:27:56.211+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:27:56.215+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:27:56.237+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:27:56.237+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:27:56.250+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:27:56.250+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:27:56.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.231 seconds
[2025-01-30T19:28:26.548+0000] {processor.py:186} INFO - Started process (PID=409) to work on /opt/airflow/dags/test.py
[2025-01-30T19:28:26.550+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:28:26.551+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:28:26.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:28:26.718+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:28:26.718+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:28:26.721+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:28:26.748+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:28:26.748+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:28:26.767+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:28:26.767+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:28:26.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.246 seconds
[2025-01-30T19:28:56.945+0000] {processor.py:186} INFO - Started process (PID=421) to work on /opt/airflow/dags/test.py
[2025-01-30T19:28:56.946+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:28:56.948+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:28:56.948+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:28:57.122+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:28:57.121+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:28:57.124+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:28:57.149+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:28:57.149+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:28:57.168+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:28:57.167+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:28:57.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.247 seconds
[2025-01-30T19:29:28.025+0000] {processor.py:186} INFO - Started process (PID=433) to work on /opt/airflow/dags/test.py
[2025-01-30T19:29:28.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:29:28.028+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:29:28.028+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:29:28.202+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:29:28.201+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:29:28.205+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:29:28.233+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:29:28.233+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:29:28.249+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:29:28.249+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:29:28.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.250 seconds
[2025-01-30T19:29:58.953+0000] {processor.py:186} INFO - Started process (PID=445) to work on /opt/airflow/dags/test.py
[2025-01-30T19:29:58.953+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:29:58.956+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:29:58.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:29:59.127+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:29:59.126+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:29:59.130+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:29:59.152+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:29:59.152+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:29:59.166+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:29:59.165+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:29:59.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.235 seconds
[2025-01-30T19:30:29.849+0000] {processor.py:186} INFO - Started process (PID=457) to work on /opt/airflow/dags/test.py
[2025-01-30T19:30:29.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:30:29.853+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:30:29.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:30:30.160+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:30:30.158+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:30:30.163+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:30:30.188+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:30:30.188+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:30:30.208+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:30:30.207+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:30:30.234+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.392 seconds
[2025-01-30T19:31:00.317+0000] {processor.py:186} INFO - Started process (PID=475) to work on /opt/airflow/dags/test.py
[2025-01-30T19:31:00.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:31:00.320+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:31:00.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:31:00.529+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:31:00.528+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:31:00.531+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:31:00.554+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:31:00.554+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:31:00.568+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:31:00.568+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:31:00.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.271 seconds
[2025-01-30T19:31:30.725+0000] {processor.py:186} INFO - Started process (PID=487) to work on /opt/airflow/dags/test.py
[2025-01-30T19:31:30.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:31:30.728+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:31:30.728+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:31:30.903+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:31:30.902+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:31:30.905+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:31:30.933+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:31:30.932+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:31:30.945+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:31:30.944+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:31:30.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.240 seconds
[2025-01-30T19:32:01.125+0000] {processor.py:186} INFO - Started process (PID=499) to work on /opt/airflow/dags/test.py
[2025-01-30T19:32:01.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:32:01.128+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:32:01.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:32:01.307+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:32:01.306+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:32:01.309+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:32:01.333+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:32:01.333+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:32:01.350+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:32:01.350+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:32:01.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.249 seconds
[2025-01-30T19:32:32.193+0000] {processor.py:186} INFO - Started process (PID=511) to work on /opt/airflow/dags/test.py
[2025-01-30T19:32:32.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:32:32.196+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:32:32.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:32:32.369+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:32:32.368+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:32:32.372+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:32:32.396+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:32:32.396+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:32:32.409+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:32:32.408+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:32:32.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.238 seconds
[2025-01-30T19:33:03.089+0000] {processor.py:186} INFO - Started process (PID=523) to work on /opt/airflow/dags/test.py
[2025-01-30T19:33:03.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:33:03.093+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:33:03.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:33:03.396+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:33:03.395+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:33:03.398+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:33:03.419+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:33:03.418+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:33:03.431+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:33:03.431+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:33:03.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.371 seconds
[2025-01-30T19:33:34.147+0000] {processor.py:186} INFO - Started process (PID=535) to work on /opt/airflow/dags/test.py
[2025-01-30T19:33:34.148+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:33:34.151+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:33:34.150+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:33:34.315+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:33:34.314+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:33:34.317+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:33:34.338+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:33:34.338+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:33:34.351+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:33:34.351+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:33:34.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.224 seconds
[2025-01-30T19:34:05.179+0000] {processor.py:186} INFO - Started process (PID=547) to work on /opt/airflow/dags/test.py
[2025-01-30T19:34:05.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:34:05.182+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:34:05.182+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:34:05.350+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:34:05.349+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:34:05.352+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:34:05.379+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:34:05.379+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:34:05.393+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:34:05.393+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:34:05.411+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.236 seconds
[2025-01-30T19:34:35.564+0000] {processor.py:186} INFO - Started process (PID=559) to work on /opt/airflow/dags/test.py
[2025-01-30T19:34:35.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:34:35.567+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:34:35.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:34:35.730+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:34:35.729+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:34:35.732+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:34:35.754+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:34:35.754+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:34:35.766+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:34:35.766+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:34:35.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.222 seconds
[2025-01-30T19:35:06.200+0000] {processor.py:186} INFO - Started process (PID=571) to work on /opt/airflow/dags/test.py
[2025-01-30T19:35:06.201+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:35:06.203+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:35:06.203+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:35:06.373+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:35:06.372+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:35:06.376+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:35:06.405+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:35:06.404+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:35:06.421+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:35:06.420+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:35:06.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.245 seconds
[2025-01-30T19:35:36.601+0000] {processor.py:186} INFO - Started process (PID=583) to work on /opt/airflow/dags/test.py
[2025-01-30T19:35:36.602+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:35:36.604+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:35:36.604+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:35:36.789+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:35:36.788+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:35:36.791+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:35:36.816+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:35:36.816+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:35:36.832+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:35:36.832+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:35:36.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.254 seconds
[2025-01-30T19:36:07.498+0000] {processor.py:186} INFO - Started process (PID=595) to work on /opt/airflow/dags/test.py
[2025-01-30T19:36:07.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:36:07.502+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:36:07.501+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:36:07.794+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:36:07.793+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:36:07.797+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:36:07.826+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:36:07.825+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:36:07.846+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:36:07.845+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:36:07.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.376 seconds
[2025-01-30T19:36:38.072+0000] {processor.py:186} INFO - Started process (PID=607) to work on /opt/airflow/dags/test.py
[2025-01-30T19:36:38.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:36:38.075+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:36:38.074+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:36:38.243+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:36:38.242+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:36:38.245+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:36:38.267+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:36:38.267+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:36:38.279+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:36:38.279+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:36:38.294+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.227 seconds
[2025-01-30T19:37:08.453+0000] {processor.py:186} INFO - Started process (PID=620) to work on /opt/airflow/dags/test.py
[2025-01-30T19:37:08.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:37:08.456+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:37:08.456+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:37:08.635+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:37:08.634+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:37:08.637+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:37:08.659+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:37:08.658+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:37:08.672+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:37:08.672+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:37:08.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.240 seconds
[2025-01-30T19:37:39.350+0000] {processor.py:186} INFO - Started process (PID=632) to work on /opt/airflow/dags/test.py
[2025-01-30T19:37:39.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:37:39.355+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:37:39.355+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:37:39.525+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:37:39.524+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:37:39.526+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:37:39.553+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:37:39.552+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:37:39.570+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:37:39.569+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:37:39.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.243 seconds
[2025-01-30T19:38:10.008+0000] {processor.py:186} INFO - Started process (PID=644) to work on /opt/airflow/dags/test.py
[2025-01-30T19:38:10.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:38:10.010+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:38:10.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:38:10.181+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:38:10.180+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:38:10.183+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:38:10.203+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:38:10.203+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:38:10.216+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:38:10.216+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:38:10.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.228 seconds
[2025-01-30T19:38:40.386+0000] {processor.py:186} INFO - Started process (PID=656) to work on /opt/airflow/dags/test.py
[2025-01-30T19:38:40.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:38:40.390+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:38:40.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:38:40.683+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:38:40.682+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:38:40.686+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:38:40.706+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:38:40.706+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:38:40.719+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:38:40.719+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:38:40.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.356 seconds
[2025-01-30T19:39:10.950+0000] {processor.py:186} INFO - Started process (PID=668) to work on /opt/airflow/dags/test.py
[2025-01-30T19:39:10.950+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:39:10.952+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:39:10.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:39:11.123+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:39:11.122+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:39:11.125+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:39:11.147+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:39:11.147+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:39:11.159+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:39:11.159+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:39:11.174+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.229 seconds
[2025-01-30T19:39:41.326+0000] {processor.py:186} INFO - Started process (PID=680) to work on /opt/airflow/dags/test.py
[2025-01-30T19:39:41.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:39:41.329+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:39:41.329+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:39:41.498+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:39:41.497+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:39:41.501+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:39:41.529+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:39:41.528+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:39:41.545+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:39:41.545+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:39:41.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.244 seconds
[2025-01-30T19:40:11.735+0000] {processor.py:186} INFO - Started process (PID=693) to work on /opt/airflow/dags/test.py
[2025-01-30T19:40:11.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:40:11.738+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:40:11.737+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:40:11.911+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:40:11.909+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:40:11.913+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:40:11.940+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:40:11.939+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:40:11.956+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:40:11.955+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:40:11.974+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.244 seconds
[2025-01-30T19:40:42.639+0000] {processor.py:186} INFO - Started process (PID=705) to work on /opt/airflow/dags/test.py
[2025-01-30T19:40:42.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:40:42.642+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:40:42.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:40:42.807+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:40:42.806+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:40:42.809+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:40:42.832+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:40:42.831+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:40:42.847+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:40:42.847+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:40:42.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.230 seconds
[2025-01-30T19:41:13.710+0000] {processor.py:186} INFO - Started process (PID=717) to work on /opt/airflow/dags/test.py
[2025-01-30T19:41:13.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:41:13.713+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:41:13.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:41:13.884+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:41:13.883+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:41:13.886+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:41:13.912+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:41:13.911+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:41:13.927+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:41:13.926+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:41:13.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.238 seconds
[2025-01-30T19:41:44.763+0000] {processor.py:186} INFO - Started process (PID=729) to work on /opt/airflow/dags/test.py
[2025-01-30T19:41:44.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:41:44.767+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:41:44.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:41:44.938+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:41:44.937+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:41:44.940+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:41:44.967+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:41:44.967+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:41:44.983+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:41:44.983+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:41:44.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.242 seconds
[2025-01-30T19:42:15.819+0000] {processor.py:186} INFO - Started process (PID=741) to work on /opt/airflow/dags/test.py
[2025-01-30T19:42:15.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:42:15.821+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:42:15.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:42:15.990+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:42:15.989+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:42:15.992+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:42:16.012+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:42:16.012+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:42:16.025+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:42:16.025+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:42:16.040+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.225 seconds
[2025-01-30T19:42:46.684+0000] {processor.py:186} INFO - Started process (PID=752) to work on /opt/airflow/dags/test.py
[2025-01-30T19:42:46.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:42:46.687+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:42:46.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:42:46.853+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:42:46.852+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:42:46.855+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:42:46.876+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:42:46.875+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:42:46.888+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:42:46.888+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:42:46.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.225 seconds
[2025-01-30T19:43:17.065+0000] {processor.py:186} INFO - Started process (PID=764) to work on /opt/airflow/dags/test.py
[2025-01-30T19:43:17.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:43:17.067+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:43:17.067+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:43:17.234+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:43:17.233+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:43:17.236+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:43:17.258+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:43:17.257+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:43:17.272+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:43:17.271+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:43:17.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.227 seconds
[2025-01-30T19:43:48.096+0000] {processor.py:186} INFO - Started process (PID=776) to work on /opt/airflow/dags/test.py
[2025-01-30T19:43:48.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:43:48.099+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:43:48.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:43:48.263+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:43:48.262+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:43:48.266+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:43:48.286+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:43:48.286+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:43:48.299+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:43:48.298+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:43:48.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.223 seconds
[2025-01-30T19:44:19.123+0000] {processor.py:186} INFO - Started process (PID=788) to work on /opt/airflow/dags/test.py
[2025-01-30T19:44:19.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:44:19.126+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:44:19.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:44:19.419+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:44:19.418+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:44:19.422+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:44:19.451+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:44:19.450+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:44:19.468+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:44:19.468+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:44:19.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.368 seconds
[2025-01-30T19:44:49.662+0000] {processor.py:186} INFO - Started process (PID=800) to work on /opt/airflow/dags/test.py
[2025-01-30T19:44:49.663+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:44:49.665+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:44:49.665+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:44:49.829+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:44:49.828+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:44:49.831+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:44:49.852+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:44:49.852+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:44:49.864+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:44:49.864+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:44:49.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.222 seconds
[2025-01-30T19:45:20.092+0000] {processor.py:186} INFO - Started process (PID=812) to work on /opt/airflow/dags/test.py
[2025-01-30T19:45:20.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:45:20.094+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:45:20.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:45:20.259+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:45:20.258+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:45:20.261+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:45:20.283+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:45:20.282+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:45:20.295+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:45:20.295+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:45:20.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.227 seconds
[2025-01-30T19:45:50.465+0000] {processor.py:186} INFO - Started process (PID=824) to work on /opt/airflow/dags/test.py
[2025-01-30T19:45:50.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:45:50.467+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:45:50.467+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:45:50.646+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:45:50.645+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:45:50.649+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:45:50.677+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:45:50.676+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:45:50.695+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:45:50.695+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:45:50.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.254 seconds
[2025-01-30T19:46:21.521+0000] {processor.py:186} INFO - Started process (PID=836) to work on /opt/airflow/dags/test.py
[2025-01-30T19:46:21.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:46:21.523+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:46:21.523+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:46:21.691+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:46:21.690+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:46:21.694+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:46:21.721+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:46:21.721+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:46:21.734+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:46:21.734+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:46:21.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.234 seconds
[2025-01-30T19:46:52.556+0000] {processor.py:186} INFO - Started process (PID=848) to work on /opt/airflow/dags/test.py
[2025-01-30T19:46:52.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:46:52.561+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:46:52.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:46:52.762+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:46:52.761+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:46:52.765+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:46:52.791+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:46:52.791+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:46:52.807+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:46:52.807+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:46:52.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.277 seconds
[2025-01-30T19:47:23.632+0000] {processor.py:186} INFO - Started process (PID=860) to work on /opt/airflow/dags/test.py
[2025-01-30T19:47:23.633+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:47:23.635+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:47:23.635+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:47:23.809+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:47:23.808+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:47:23.811+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:47:23.837+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:47:23.837+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:47:23.855+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:47:23.854+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:47:23.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.247 seconds
[2025-01-30T19:47:54.442+0000] {processor.py:186} INFO - Started process (PID=872) to work on /opt/airflow/dags/test.py
[2025-01-30T19:47:54.444+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:47:54.446+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:47:54.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:47:54.675+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:47:54.674+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:47:54.677+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:47:54.698+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:47:54.697+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:47:54.711+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:47:54.711+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:47:54.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.290 seconds
[2025-01-30T19:48:25.344+0000] {processor.py:186} INFO - Started process (PID=884) to work on /opt/airflow/dags/test.py
[2025-01-30T19:48:25.344+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:48:25.347+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:48:25.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:48:25.635+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:48:25.634+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:48:25.637+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:48:25.664+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:48:25.663+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:48:25.683+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:48:25.682+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:48:25.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.362 seconds
[2025-01-30T19:48:55.892+0000] {processor.py:186} INFO - Started process (PID=897) to work on /opt/airflow/dags/test.py
[2025-01-30T19:48:55.894+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:48:55.895+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:48:55.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:48:56.061+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:48:56.060+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:48:56.063+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:48:56.084+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:48:56.084+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:48:56.097+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:48:56.097+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:48:56.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.226 seconds
[2025-01-30T19:49:26.269+0000] {processor.py:186} INFO - Started process (PID=909) to work on /opt/airflow/dags/test.py
[2025-01-30T19:49:26.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:49:26.272+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:49:26.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:49:26.441+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:49:26.441+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:49:26.444+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:49:26.469+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:49:26.469+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:49:26.486+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:49:26.486+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:49:26.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.241 seconds
[2025-01-30T19:49:56.760+0000] {processor.py:186} INFO - Started process (PID=921) to work on /opt/airflow/dags/test.py
[2025-01-30T19:49:56.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:49:56.763+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:49:56.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:49:56.928+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:49:56.927+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:49:56.930+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:49:56.950+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:49:56.950+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:49:56.963+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:49:56.962+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:49:56.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.223 seconds
[2025-01-30T19:50:27.421+0000] {processor.py:186} INFO - Started process (PID=933) to work on /opt/airflow/dags/test.py
[2025-01-30T19:50:27.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:50:27.423+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:50:27.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:50:27.599+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:50:27.597+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:50:27.601+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:50:27.631+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:50:27.631+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:50:27.650+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:50:27.650+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:50:27.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.251 seconds
[2025-01-30T19:50:58.480+0000] {processor.py:186} INFO - Started process (PID=945) to work on /opt/airflow/dags/test.py
[2025-01-30T19:50:58.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:50:58.483+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:50:58.483+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:50:58.660+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:50:58.659+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:50:58.663+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:50:58.691+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:50:58.691+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:50:58.707+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:50:58.706+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:50:58.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.248 seconds
[2025-01-30T19:51:29.528+0000] {processor.py:186} INFO - Started process (PID=957) to work on /opt/airflow/dags/test.py
[2025-01-30T19:51:29.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:51:29.530+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:51:29.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:51:29.709+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:51:29.708+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:51:29.711+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:51:29.738+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:51:29.738+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:51:29.754+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:51:29.754+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:51:29.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.250 seconds
[2025-01-30T19:52:00.606+0000] {processor.py:186} INFO - Started process (PID=969) to work on /opt/airflow/dags/test.py
[2025-01-30T19:52:00.607+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:52:00.609+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:52:00.609+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:52:00.780+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:52:00.779+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:52:00.782+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:52:00.811+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:52:00.810+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:52:00.829+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:52:00.828+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:52:00.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.247 seconds
[2025-01-30T19:52:31.700+0000] {processor.py:186} INFO - Started process (PID=982) to work on /opt/airflow/dags/test.py
[2025-01-30T19:52:31.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:52:31.703+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:52:31.703+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:52:31.994+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:52:31.993+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:52:31.997+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:52:32.025+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:52:32.025+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:52:32.043+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:52:32.043+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:52:32.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.369 seconds
[2025-01-30T19:53:02.655+0000] {processor.py:186} INFO - Started process (PID=1000) to work on /opt/airflow/dags/test.py
[2025-01-30T19:53:02.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:53:02.660+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:53:02.660+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:53:02.964+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:53:02.963+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:53:02.967+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:53:02.997+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:53:02.996+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:53:03.012+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:53:03.012+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:53:03.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.391 seconds
[2025-01-30T19:53:33.854+0000] {processor.py:186} INFO - Started process (PID=1012) to work on /opt/airflow/dags/test.py
[2025-01-30T19:53:33.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:53:33.857+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:53:33.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:53:34.022+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:53:34.021+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:53:34.025+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:53:34.052+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:53:34.052+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:53:34.068+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:53:34.068+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:53:34.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.238 seconds
[2025-01-30T19:54:04.903+0000] {processor.py:186} INFO - Started process (PID=1024) to work on /opt/airflow/dags/test.py
[2025-01-30T19:54:04.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:54:04.906+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:54:04.906+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:54:05.074+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:54:05.074+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:54:05.077+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:54:05.097+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:54:05.097+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:54:05.109+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:54:05.108+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:54:05.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.225 seconds
[2025-01-30T19:54:35.299+0000] {processor.py:186} INFO - Started process (PID=1036) to work on /opt/airflow/dags/test.py
[2025-01-30T19:54:35.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:54:35.301+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:54:35.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:54:35.468+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:54:35.467+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:54:35.470+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:54:35.490+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:54:35.490+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:54:35.502+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:54:35.502+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:54:35.519+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.226 seconds
[2025-01-30T19:55:05.658+0000] {processor.py:186} INFO - Started process (PID=1048) to work on /opt/airflow/dags/test.py
[2025-01-30T19:55:05.660+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:55:05.662+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:55:05.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:55:05.849+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:55:05.848+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:55:05.851+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:55:05.871+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:55:05.871+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:55:05.884+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:55:05.884+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:55:05.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.251 seconds
[2025-01-30T19:55:36.320+0000] {processor.py:186} INFO - Started process (PID=1060) to work on /opt/airflow/dags/test.py
[2025-01-30T19:55:36.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:55:36.322+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:55:36.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:55:36.491+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:55:36.490+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:55:36.494+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:55:36.522+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:55:36.522+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:55:36.541+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:55:36.540+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:55:36.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.243 seconds
[2025-01-30T19:56:06.588+0000] {processor.py:186} INFO - Started process (PID=1073) to work on /opt/airflow/dags/test.py
[2025-01-30T19:56:06.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:56:06.592+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:56:06.591+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:56:06.757+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:56:06.756+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:56:06.759+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:56:06.787+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:56:06.787+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:56:06.803+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:56:06.803+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:56:06.822+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.239 seconds
[2025-01-30T19:56:37.400+0000] {processor.py:186} INFO - Started process (PID=1085) to work on /opt/airflow/dags/test.py
[2025-01-30T19:56:37.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:56:37.403+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:56:37.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:56:37.610+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:56:37.609+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:56:37.613+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:56:37.640+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:56:37.640+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:56:37.653+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:56:37.653+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:56:37.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.276 seconds
[2025-01-30T19:57:08.460+0000] {processor.py:186} INFO - Started process (PID=1097) to work on /opt/airflow/dags/test.py
[2025-01-30T19:57:08.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:57:08.466+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:57:08.465+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:57:08.759+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:57:08.758+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:57:08.762+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:57:08.790+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:57:08.790+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:57:08.808+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:57:08.808+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:57:08.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.376 seconds
[2025-01-30T19:57:39.364+0000] {processor.py:186} INFO - Started process (PID=1109) to work on /opt/airflow/dags/test.py
[2025-01-30T19:57:39.365+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:57:39.367+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:57:39.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:57:39.537+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:57:39.535+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:57:39.539+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:57:39.568+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:57:39.568+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:57:39.585+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:57:39.585+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:57:39.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.244 seconds
[2025-01-30T19:58:09.781+0000] {processor.py:186} INFO - Started process (PID=1121) to work on /opt/airflow/dags/test.py
[2025-01-30T19:58:09.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:58:09.785+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:58:09.784+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:58:09.952+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:58:09.951+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:58:09.955+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:58:09.982+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:58:09.981+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:58:09.999+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:58:09.999+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:58:10.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.239 seconds
[2025-01-30T19:58:40.187+0000] {processor.py:186} INFO - Started process (PID=1133) to work on /opt/airflow/dags/test.py
[2025-01-30T19:58:40.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:58:40.190+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:58:40.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:58:40.360+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:58:40.359+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:58:40.362+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:58:40.387+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:58:40.387+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:58:40.400+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:58:40.399+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:58:40.415+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.234 seconds
[2025-01-30T19:59:10.443+0000] {processor.py:186} INFO - Started process (PID=1146) to work on /opt/airflow/dags/test.py
[2025-01-30T19:59:10.444+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T19:59:10.446+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:59:10.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T19:59:10.618+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:59:10.617+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T19:59:10.620+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T19:59:10.647+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:59:10.647+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T19:59:10.664+0000] {logging_mixin.py:190} INFO - [2025-01-30T19:59:10.663+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T19:59:10.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.245 seconds
[2025-01-30T20:10:59.614+0000] {processor.py:186} INFO - Started process (PID=36) to work on /opt/airflow/dags/test.py
[2025-01-30T20:10:59.615+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:10:59.620+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:10:59.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:10:59.958+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:10:59.955+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:10:59.960+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:11:00.006+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:11:00.005+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:11:00.025+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:11:00.025+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:11:00.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.454 seconds
[2025-01-30T20:11:30.068+0000] {processor.py:186} INFO - Started process (PID=47) to work on /opt/airflow/dags/test.py
[2025-01-30T20:11:30.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:11:30.070+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:11:30.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:11:30.233+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:11:30.232+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:11:30.235+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:11:30.261+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:11:30.260+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:11:30.277+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:11:30.277+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:11:30.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.234 seconds
[2025-01-30T20:12:00.817+0000] {processor.py:186} INFO - Started process (PID=58) to work on /opt/airflow/dags/test.py
[2025-01-30T20:12:00.818+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:12:00.820+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:12:00.820+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:12:00.987+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:12:00.986+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:12:00.989+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:12:01.011+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:12:01.010+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:12:01.183+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:12:01.183+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:12:01.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.406 seconds
[2025-01-30T20:12:31.392+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/test.py
[2025-01-30T20:12:31.392+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:12:31.394+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:12:31.394+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:12:31.556+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:12:31.555+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:12:31.558+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:12:31.579+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:12:31.579+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:12:31.703+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:12:31.702+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:12:31.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.329 seconds
[2025-01-30T20:13:01.818+0000] {processor.py:186} INFO - Started process (PID=81) to work on /opt/airflow/dags/test.py
[2025-01-30T20:13:01.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:13:01.821+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:13:01.820+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:13:01.991+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:13:01.990+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:13:01.992+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:13:02.136+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:13:02.136+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:13:02.147+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:13:02.147+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:13:02.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.347 seconds
[2025-01-30T20:13:32.435+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/test.py
[2025-01-30T20:13:32.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:13:32.437+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:13:32.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:13:32.720+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:13:32.719+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:13:32.722+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:13:32.738+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:13:32.738+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:13:32.749+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:13:32.748+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:13:32.761+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.331 seconds
[2025-01-30T20:14:02.791+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/test.py
[2025-01-30T20:14:02.792+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:14:02.793+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:14:02.793+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:14:03.082+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:14:03.081+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:14:03.084+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:14:03.105+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:14:03.105+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:14:03.119+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:14:03.119+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:14:03.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.346 seconds
[2025-01-30T20:14:33.394+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/test.py
[2025-01-30T20:14:33.396+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:14:33.397+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:14:33.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:14:33.560+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:14:33.559+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:14:33.562+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:14:33.581+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:14:33.581+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:14:33.593+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:14:33.593+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:14:33.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.217 seconds
[2025-01-30T20:15:04.383+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/test.py
[2025-01-30T20:15:04.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:15:04.385+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:15:04.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:15:04.570+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:15:04.569+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:15:04.573+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:15:04.600+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:15:04.599+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:15:04.612+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:15:04.612+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:15:04.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.248 seconds
[2025-01-30T20:15:35.241+0000] {processor.py:186} INFO - Started process (PID=146) to work on /opt/airflow/dags/test.py
[2025-01-30T20:15:35.242+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:15:35.243+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:15:35.243+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:15:35.404+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:15:35.403+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:15:35.406+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:15:35.426+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:15:35.426+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:15:35.439+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:15:35.439+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:15:35.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.216 seconds
[2025-01-30T20:16:06.095+0000] {processor.py:186} INFO - Started process (PID=158) to work on /opt/airflow/dags/test.py
[2025-01-30T20:16:06.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:16:06.098+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:16:06.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:16:06.258+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:16:06.258+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:16:06.260+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:16:06.281+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:16:06.281+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:16:06.296+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:16:06.296+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:16:06.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.223 seconds
[2025-01-30T20:16:36.709+0000] {processor.py:186} INFO - Started process (PID=170) to work on /opt/airflow/dags/test.py
[2025-01-30T20:16:36.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:16:36.711+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:16:36.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:16:36.997+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:16:36.996+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:16:37.000+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:16:37.026+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:16:37.026+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:16:37.042+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:16:37.042+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:16:37.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.355 seconds
[2025-01-30T20:17:07.217+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/dags/test.py
[2025-01-30T20:17:07.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:17:07.219+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:17:07.219+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:17:07.378+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:17:07.377+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:17:07.380+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:17:07.403+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:17:07.403+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:17:07.416+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:17:07.416+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:17:07.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.218 seconds
[2025-01-30T20:17:38.065+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/test.py
[2025-01-30T20:17:38.072+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:17:38.074+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:17:38.074+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:17:38.372+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:17:38.371+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:17:38.374+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:17:38.401+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:17:38.401+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:17:38.417+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:17:38.416+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:17:38.434+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.373 seconds
[2025-01-30T20:18:08.807+0000] {processor.py:186} INFO - Started process (PID=206) to work on /opt/airflow/dags/test.py
[2025-01-30T20:18:08.807+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:18:08.809+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:18:08.809+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:18:09.101+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:18:09.100+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:18:09.104+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:18:09.131+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:18:09.131+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:18:09.147+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:18:09.147+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:18:09.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.364 seconds
[2025-01-30T20:18:39.812+0000] {processor.py:186} INFO - Started process (PID=218) to work on /opt/airflow/dags/test.py
[2025-01-30T20:18:39.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:18:39.815+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:18:39.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:18:40.100+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:18:40.099+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:18:40.103+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:18:40.128+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:18:40.128+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:18:40.145+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:18:40.145+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:18:40.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.359 seconds
[2025-01-30T20:19:10.892+0000] {processor.py:186} INFO - Started process (PID=230) to work on /opt/airflow/dags/test.py
[2025-01-30T20:19:10.894+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:19:10.896+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:19:10.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:19:11.058+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:19:11.057+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:19:11.060+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:19:11.085+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:19:11.085+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:19:11.101+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:19:11.101+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:19:11.116+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.228 seconds
[2025-01-30T20:19:41.956+0000] {processor.py:186} INFO - Started process (PID=243) to work on /opt/airflow/dags/test.py
[2025-01-30T20:19:41.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:19:41.959+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:19:41.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:19:42.118+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:19:42.118+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:19:42.120+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:19:42.140+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:19:42.140+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:19:42.153+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:19:42.153+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:19:42.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.216 seconds
[2025-01-30T20:20:13.110+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/test.py
[2025-01-30T20:20:13.111+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:20:13.112+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:20:13.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:20:13.276+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:20:13.276+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:20:13.279+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:20:13.305+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:20:13.305+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:20:13.320+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:20:13.320+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:20:13.338+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.232 seconds
[2025-01-30T20:20:43.989+0000] {processor.py:186} INFO - Started process (PID=266) to work on /opt/airflow/dags/test.py
[2025-01-30T20:20:43.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:20:43.991+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:20:43.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:20:44.153+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:20:44.152+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:20:44.155+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:20:44.174+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:20:44.174+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:20:44.185+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:20:44.185+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:20:44.200+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.216 seconds
[2025-01-30T20:21:14.840+0000] {processor.py:186} INFO - Started process (PID=278) to work on /opt/airflow/dags/test.py
[2025-01-30T20:21:14.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:21:14.843+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:21:14.843+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:21:15.000+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:21:14.999+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:21:15.002+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:21:15.022+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:21:15.022+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:21:15.035+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:21:15.035+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:21:15.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.214 seconds
[2025-01-30T20:21:45.483+0000] {processor.py:186} INFO - Started process (PID=290) to work on /opt/airflow/dags/test.py
[2025-01-30T20:21:45.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:21:45.485+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:21:45.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:21:45.706+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:21:45.705+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:21:45.708+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:21:45.735+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:21:45.735+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:21:45.751+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:21:45.751+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:21:45.767+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.289 seconds
[2025-01-30T20:22:16.455+0000] {processor.py:186} INFO - Started process (PID=302) to work on /opt/airflow/dags/test.py
[2025-01-30T20:22:16.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:22:16.457+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:22:16.457+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:22:16.629+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:22:16.629+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:22:16.631+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:22:16.656+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:22:16.656+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:22:16.674+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:22:16.674+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:22:16.690+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.240 seconds
[2025-01-30T20:22:47.445+0000] {processor.py:186} INFO - Started process (PID=314) to work on /opt/airflow/dags/test.py
[2025-01-30T20:22:47.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:22:47.448+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:22:47.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:22:47.612+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:22:47.611+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:22:47.615+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:22:47.641+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:22:47.641+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:22:47.657+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:22:47.657+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:22:47.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.234 seconds
[2025-01-30T20:23:18.299+0000] {processor.py:186} INFO - Started process (PID=326) to work on /opt/airflow/dags/test.py
[2025-01-30T20:23:18.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:23:18.302+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:23:18.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:23:18.464+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:23:18.463+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:23:18.466+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:23:18.486+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:23:18.486+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:23:18.498+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:23:18.498+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:23:18.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.218 seconds
[2025-01-30T20:23:49.075+0000] {processor.py:186} INFO - Started process (PID=338) to work on /opt/airflow/dags/test.py
[2025-01-30T20:23:49.075+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:23:49.077+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:23:49.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:23:49.262+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:23:49.261+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:23:49.265+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:23:49.288+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:23:49.288+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:23:49.300+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:23:49.300+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:23:49.314+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.245 seconds
[2025-01-30T20:24:19.933+0000] {processor.py:186} INFO - Started process (PID=350) to work on /opt/airflow/dags/test.py
[2025-01-30T20:24:19.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:24:19.936+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:24:19.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:24:20.096+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:24:20.095+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:24:20.098+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:24:20.119+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:24:20.118+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:24:20.131+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:24:20.130+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:24:20.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.219 seconds
[2025-01-30T20:24:50.548+0000] {processor.py:186} INFO - Started process (PID=362) to work on /opt/airflow/dags/test.py
[2025-01-30T20:24:50.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:24:50.550+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:24:50.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:24:50.711+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:24:50.710+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:24:50.713+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:24:50.734+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:24:50.734+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:24:50.748+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:24:50.747+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:24:50.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.221 seconds
[2025-01-30T20:25:20.920+0000] {processor.py:186} INFO - Started process (PID=374) to work on /opt/airflow/dags/test.py
[2025-01-30T20:25:20.922+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:25:20.923+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:25:20.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:25:21.091+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:25:21.090+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:25:21.093+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:25:21.120+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:25:21.120+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:25:21.136+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:25:21.136+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:25:21.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.238 seconds
[2025-01-30T20:25:51.791+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/airflow/dags/test.py
[2025-01-30T20:25:51.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:25:51.793+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:25:51.793+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:25:51.961+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:25:51.960+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:25:51.963+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:25:51.984+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:25:51.984+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:25:51.998+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:25:51.997+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:25:52.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.229 seconds
[2025-01-30T20:26:22.640+0000] {processor.py:186} INFO - Started process (PID=398) to work on /opt/airflow/dags/test.py
[2025-01-30T20:26:22.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:26:22.643+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:26:22.643+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:26:22.805+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:26:22.804+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:26:22.807+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:26:22.834+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:26:22.834+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:26:22.850+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:26:22.850+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:26:22.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.229 seconds
[2025-01-30T20:26:53.530+0000] {processor.py:186} INFO - Started process (PID=410) to work on /opt/airflow/dags/test.py
[2025-01-30T20:26:53.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:26:53.534+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:26:53.534+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:26:53.834+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:26:53.833+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:26:53.837+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:26:53.858+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:26:53.858+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:26:53.871+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:26:53.871+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:26:53.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.362 seconds
[2025-01-30T20:27:24.540+0000] {processor.py:186} INFO - Started process (PID=422) to work on /opt/airflow/dags/test.py
[2025-01-30T20:27:24.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-30T20:27:24.544+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:27:24.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-30T20:27:24.831+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:27:24.830+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-30T20:27:24.834+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-30T20:27:24.861+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:27:24.861+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-30T20:27:24.876+0000] {logging_mixin.py:190} INFO - [2025-01-30T20:27:24.876+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-30T20:27:24.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.357 seconds
