[2025-01-14T21:02:48.808+0000] {processor.py:186} INFO - Started process (PID=32) to work on /opt/airflow/dags/test.py
[2025-01-14T21:02:48.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:02:48.819+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:02:48.818+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:02:49.173+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:02:49.172+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:02:49.176+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:02:49.494+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:02:49.493+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:test
[2025-01-14T21:02:49.506+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:02:49.506+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:test
[2025-01-14T21:02:49.513+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:02:49.513+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:test
[2025-01-14T21:02:49.521+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:02:49.521+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:test
[2025-01-14T21:02:49.530+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:02:49.530+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:test
[2025-01-14T21:02:49.539+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:02:49.539+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:test
[2025-01-14T21:02:49.546+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:02:49.546+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:test
[2025-01-14T21:02:49.547+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:02:49.547+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:02:49.573+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:02:49.573+0000] {dag.py:3262} INFO - Creating ORM DAG for test
[2025-01-14T21:02:49.574+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:02:49.574+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:02:49.610+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.814 seconds
[2025-01-14T21:03:19.996+0000] {processor.py:186} INFO - Started process (PID=40) to work on /opt/airflow/dags/test.py
[2025-01-14T21:03:19.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:03:20.000+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:03:20.000+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:03:20.169+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:03:20.168+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:03:20.171+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:03:20.194+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:03:20.194+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:03:20.208+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:03:20.207+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:03:20.224+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.234 seconds
[2025-01-14T21:03:50.394+0000] {processor.py:186} INFO - Started process (PID=49) to work on /opt/airflow/dags/test.py
[2025-01-14T21:03:50.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:03:50.397+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:03:50.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:03:50.706+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:03:50.705+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:03:50.708+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:03:50.731+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:03:50.731+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:03:50.744+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:03:50.744+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:03:50.760+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.375 seconds
[2025-01-14T21:04:20.866+0000] {processor.py:186} INFO - Started process (PID=58) to work on /opt/airflow/dags/test.py
[2025-01-14T21:04:20.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:04:20.869+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:04:20.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:04:21.039+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:04:21.038+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:04:21.043+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:04:21.071+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:04:21.071+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:04:21.088+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:04:21.088+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:04:21.108+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.247 seconds
[2025-01-14T21:04:51.275+0000] {processor.py:186} INFO - Started process (PID=67) to work on /opt/airflow/dags/test.py
[2025-01-14T21:04:51.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:04:51.278+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:04:51.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:04:51.451+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:04:51.450+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:04:51.453+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:04:51.477+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:04:51.476+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:04:51.489+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:04:51.489+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:04:51.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.235 seconds
[2025-01-14T21:05:21.671+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/test.py
[2025-01-14T21:05:21.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:05:21.674+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:05:21.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:05:21.848+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:05:21.847+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:05:21.850+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:05:21.872+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:05:21.872+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:05:21.885+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:05:21.884+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:05:21.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.239 seconds
[2025-01-14T21:05:52.067+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/test.py
[2025-01-14T21:05:52.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:05:52.070+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:05:52.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:05:52.242+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:05:52.241+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:05:52.245+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:05:52.268+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:05:52.267+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:05:52.283+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:05:52.283+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:05:52.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.397 seconds
[2025-01-14T21:06:22.626+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/test.py
[2025-01-14T21:06:22.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:06:22.629+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:06:22.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:06:22.801+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:06:22.800+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:06:22.804+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:06:22.833+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:06:22.833+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:06:23.009+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:06:23.009+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:06:23.026+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.406 seconds
[2025-01-14T21:06:53.195+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/test.py
[2025-01-14T21:06:53.196+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:06:53.198+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:06:53.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:06:53.373+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:06:53.372+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:06:53.376+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:06:53.549+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:06:53.548+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:06:53.561+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:06:53.561+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:06:53.577+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.388 seconds
[2025-01-14T21:07:23.738+0000] {processor.py:186} INFO - Started process (PID=119) to work on /opt/airflow/dags/test.py
[2025-01-14T21:07:23.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:07:23.744+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:07:23.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:07:23.942+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:07:23.941+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:07:23.944+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:07:24.115+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:07:24.115+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:07:24.131+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:07:24.130+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:07:24.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.415 seconds
[2025-01-14T21:07:54.312+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/test.py
[2025-01-14T21:07:54.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:07:54.314+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:07:54.314+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:07:54.630+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:07:54.629+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:07:54.633+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:07:54.658+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:07:54.658+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:07:54.673+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:07:54.673+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:07:54.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.386 seconds
[2025-01-14T21:08:24.852+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/test.py
[2025-01-14T21:08:24.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:08:24.857+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:08:24.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:08:25.165+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:08:25.164+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:08:25.168+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:08:25.196+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:08:25.196+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:08:25.213+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:08:25.213+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:08:25.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.391 seconds
[2025-01-14T21:08:55.408+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/test.py
[2025-01-14T21:08:55.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:08:55.412+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:08:55.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:08:55.719+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:08:55.717+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:08:55.721+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:08:55.744+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:08:55.744+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:08:55.934+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:08:55.933+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:08:55.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.560 seconds
[2025-01-14T21:09:26.148+0000] {processor.py:186} INFO - Started process (PID=156) to work on /opt/airflow/dags/test.py
[2025-01-14T21:09:26.151+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:09:26.154+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:09:26.154+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:09:26.463+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:09:26.461+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:09:26.466+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:09:26.493+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:09:26.493+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:09:26.651+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:09:26.651+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:09:26.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.526 seconds
[2025-01-14T21:09:56.875+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/dags/test.py
[2025-01-14T21:09:56.876+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:09:56.879+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:09:56.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:09:57.050+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:09:57.048+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:09:57.052+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:09:57.221+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:09:57.221+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:09:57.234+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:09:57.234+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:09:57.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.380 seconds
[2025-01-14T21:10:27.420+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/test.py
[2025-01-14T21:10:27.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:10:27.423+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:10:27.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:10:27.756+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:10:27.755+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:10:27.758+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:10:27.783+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:10:27.783+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:10:27.798+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:10:27.798+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:10:27.817+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.403 seconds
[2025-01-14T21:10:57.989+0000] {processor.py:186} INFO - Started process (PID=183) to work on /opt/airflow/dags/test.py
[2025-01-14T21:10:57.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:10:57.994+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:10:57.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:10:58.167+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:10:58.166+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:10:58.170+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:10:58.192+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:10:58.191+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:10:58.205+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:10:58.205+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:10:58.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.238 seconds
[2025-01-14T21:11:28.387+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/test.py
[2025-01-14T21:11:28.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:11:28.389+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:11:28.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:11:28.560+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:11:28.558+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:11:28.562+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:11:28.585+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:11:28.585+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:11:28.599+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:11:28.599+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:11:28.767+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.386 seconds
[2025-01-14T21:11:58.947+0000] {processor.py:186} INFO - Started process (PID=201) to work on /opt/airflow/dags/test.py
[2025-01-14T21:11:58.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:11:58.949+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:11:58.949+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:11:59.151+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:11:59.150+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:11:59.154+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:11:59.177+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:11:59.176+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:11:59.333+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:11:59.333+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:11:59.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.410 seconds
[2025-01-14T21:12:29.517+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/test.py
[2025-01-14T21:12:29.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:12:29.520+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:12:29.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:12:29.690+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:12:29.689+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:12:29.692+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:12:29.857+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:12:29.857+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:12:29.869+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:12:29.869+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:12:29.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.372 seconds
[2025-01-14T21:13:00.257+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/test.py
[2025-01-14T21:13:00.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:13:00.260+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:13:00.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:13:00.435+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:13:00.435+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:13:00.438+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:13:00.602+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:13:00.602+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:13:00.614+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:13:00.613+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:13:00.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.378 seconds
[2025-01-14T21:13:30.997+0000] {processor.py:186} INFO - Started process (PID=230) to work on /opt/airflow/dags/test.py
[2025-01-14T21:13:30.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:13:31.000+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:13:30.999+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:13:31.307+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:13:31.306+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:13:31.310+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:13:31.335+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:13:31.334+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:13:31.350+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:13:31.349+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:13:31.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.378 seconds
[2025-01-14T21:14:01.532+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/test.py
[2025-01-14T21:14:01.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:14:01.535+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:14:01.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:14:01.716+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:14:01.716+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:14:01.718+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:14:01.746+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:14:01.746+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:14:01.763+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:14:01.763+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:14:01.784+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.257 seconds
[2025-01-14T21:14:32.001+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/test.py
[2025-01-14T21:14:32.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:14:32.004+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:14:32.004+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:14:32.172+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:14:32.171+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:14:32.174+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:14:32.202+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:14:32.202+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:14:32.364+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:14:32.364+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:14:32.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.386 seconds
[2025-01-14T21:15:02.605+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/dags/test.py
[2025-01-14T21:15:02.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:15:02.609+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:15:02.608+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:15:02.894+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:15:02.893+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:15:02.897+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:15:02.931+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:15:02.930+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:15:03.124+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:15:03.124+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:15:03.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.551 seconds
[2025-01-14T21:15:33.326+0000] {processor.py:186} INFO - Started process (PID=271) to work on /opt/airflow/dags/test.py
[2025-01-14T21:15:33.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:15:33.330+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:15:33.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:15:33.642+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:15:33.641+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:15:33.645+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:15:33.858+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:15:33.857+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:15:33.874+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:15:33.874+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:15:33.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.576 seconds
[2025-01-14T21:16:04.272+0000] {processor.py:186} INFO - Started process (PID=281) to work on /opt/airflow/dags/test.py
[2025-01-14T21:16:04.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:16:04.276+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:16:04.276+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:16:04.744+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:16:04.743+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:16:04.747+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:16:04.776+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:16:04.775+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:16:04.794+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:16:04.794+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:16:04.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.551 seconds
[2025-01-14T21:16:35.005+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/test.py
[2025-01-14T21:16:35.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:16:35.010+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:16:35.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:16:35.326+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:16:35.326+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:16:35.328+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:16:35.352+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:16:35.352+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:16:35.365+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:16:35.365+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:16:35.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.383 seconds
[2025-01-14T21:17:05.554+0000] {processor.py:186} INFO - Started process (PID=301) to work on /opt/airflow/dags/test.py
[2025-01-14T21:17:05.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:17:05.557+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:17:05.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:17:05.853+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:17:05.852+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:17:05.856+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:17:05.890+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:17:05.889+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:17:05.912+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:17:05.912+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:17:06.105+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.558 seconds
[2025-01-14T21:17:36.252+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/test.py
[2025-01-14T21:17:36.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:17:36.255+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:17:36.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:17:36.427+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:17:36.426+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:17:36.430+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:17:36.454+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:17:36.454+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:17:36.617+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:17:36.617+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:17:36.636+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.389 seconds
[2025-01-14T21:18:06.863+0000] {processor.py:186} INFO - Started process (PID=321) to work on /opt/airflow/dags/test.py
[2025-01-14T21:18:06.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:18:06.865+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:18:06.865+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:18:07.035+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:18:07.034+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:18:07.037+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:18:07.215+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:18:07.215+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:18:07.227+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:18:07.226+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:18:07.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.385 seconds
[2025-01-14T21:18:37.408+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/test.py
[2025-01-14T21:18:37.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:18:37.411+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:18:37.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:18:37.726+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:18:37.725+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:18:37.728+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:18:37.748+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:18:37.747+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:18:37.760+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:18:37.760+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:18:37.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.372 seconds
[2025-01-14T21:19:08.153+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/test.py
[2025-01-14T21:19:08.155+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:19:08.157+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:19:08.156+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:19:08.466+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:19:08.465+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:19:08.468+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:19:08.492+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:19:08.492+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:19:08.508+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:19:08.508+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:19:08.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.377 seconds
[2025-01-14T21:19:38.693+0000] {processor.py:186} INFO - Started process (PID=350) to work on /opt/airflow/dags/test.py
[2025-01-14T21:19:38.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:19:38.696+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:19:38.696+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:19:38.882+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:19:38.881+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:19:38.885+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:19:38.909+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:19:38.908+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:19:38.923+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:19:38.922+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:19:39.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.394 seconds
[2025-01-14T21:20:09.252+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/test.py
[2025-01-14T21:20:09.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:20:09.255+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:20:09.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:20:09.426+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:20:09.425+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:20:09.429+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:20:09.452+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:20:09.452+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:20:09.607+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:20:09.607+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:20:09.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.376 seconds
[2025-01-14T21:20:39.858+0000] {processor.py:186} INFO - Started process (PID=371) to work on /opt/airflow/dags/test.py
[2025-01-14T21:20:39.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:20:39.861+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:20:39.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:20:40.029+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:20:40.028+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:20:40.031+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:20:40.062+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:20:40.062+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:20:40.229+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:20:40.229+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:20:40.244+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.393 seconds
[2025-01-14T21:21:10.465+0000] {processor.py:186} INFO - Started process (PID=381) to work on /opt/airflow/dags/test.py
[2025-01-14T21:21:10.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:21:10.467+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:21:10.467+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:21:10.636+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:21:10.635+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:21:10.638+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:21:10.803+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:21:10.803+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:21:10.819+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:21:10.818+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:21:10.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.376 seconds
[2025-01-14T21:21:41.008+0000] {processor.py:186} INFO - Started process (PID=390) to work on /opt/airflow/dags/test.py
[2025-01-14T21:21:41.009+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:21:41.011+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:21:41.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:21:41.374+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:21:41.373+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:21:41.376+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:21:41.402+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:21:41.402+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:21:41.418+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:21:41.417+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:21:41.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.438 seconds
[2025-01-14T21:22:11.852+0000] {processor.py:186} INFO - Started process (PID=400) to work on /opt/airflow/dags/test.py
[2025-01-14T21:22:11.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:22:11.855+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:22:11.854+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:22:12.170+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:22:12.169+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:22:12.172+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:22:12.192+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:22:12.191+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:22:12.205+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:22:12.204+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:22:12.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.374 seconds
[2025-01-14T21:22:42.601+0000] {processor.py:186} INFO - Started process (PID=411) to work on /opt/airflow/dags/test.py
[2025-01-14T21:22:42.602+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:22:42.605+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:22:42.605+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:22:42.775+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:22:42.773+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:22:42.777+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:22:42.799+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:22:42.799+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:22:42.814+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:22:42.813+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:22:42.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.378 seconds
[2025-01-14T21:23:13.162+0000] {processor.py:186} INFO - Started process (PID=421) to work on /opt/airflow/dags/test.py
[2025-01-14T21:23:13.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:23:13.167+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:23:13.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:23:13.462+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:23:13.460+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:23:13.465+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:23:13.496+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:23:13.496+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:23:13.661+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:23:13.660+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:23:13.680+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.526 seconds
[2025-01-14T21:23:43.846+0000] {processor.py:186} INFO - Started process (PID=430) to work on /opt/airflow/dags/test.py
[2025-01-14T21:23:43.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:23:43.849+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:23:43.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:23:44.020+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:23:44.018+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:23:44.022+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:23:44.192+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:23:44.192+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:23:44.204+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:23:44.203+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:23:44.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.380 seconds
[2025-01-14T21:24:14.447+0000] {processor.py:186} INFO - Started process (PID=442) to work on /opt/airflow/dags/test.py
[2025-01-14T21:24:14.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:24:14.450+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:24:14.450+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:24:14.772+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:24:14.771+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:24:14.775+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:24:14.795+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:24:14.795+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:24:14.807+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:24:14.807+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:24:14.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.381 seconds
[2025-01-14T21:24:44.990+0000] {processor.py:186} INFO - Started process (PID=452) to work on /opt/airflow/dags/test.py
[2025-01-14T21:24:44.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:24:44.993+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:24:44.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:24:45.306+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:24:45.305+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:24:45.308+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:24:45.328+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:24:45.328+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:24:45.340+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:24:45.340+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:24:45.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.370 seconds
[2025-01-14T21:25:15.733+0000] {processor.py:186} INFO - Started process (PID=462) to work on /opt/airflow/dags/test.py
[2025-01-14T21:25:15.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:25:15.739+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:25:15.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:25:16.040+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:25:16.039+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:25:16.043+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:25:16.067+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:25:16.067+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:25:16.080+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:25:16.080+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:25:16.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.514 seconds
[2025-01-14T21:25:46.552+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/test.py
[2025-01-14T21:25:46.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:25:46.555+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:25:46.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:25:46.724+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:25:46.723+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:25:46.726+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:25:46.750+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:25:46.749+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:25:46.909+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:25:46.908+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:25:46.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.378 seconds
[2025-01-14T21:26:17.175+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/test.py
[2025-01-14T21:26:17.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:26:17.178+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:26:17.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:26:17.344+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:26:17.343+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:26:17.346+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:26:17.511+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:26:17.511+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:26:17.522+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:26:17.522+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:26:17.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.369 seconds
[2025-01-14T21:26:47.688+0000] {processor.py:186} INFO - Started process (PID=493) to work on /opt/airflow/dags/test.py
[2025-01-14T21:26:47.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:26:47.691+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:26:47.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:26:47.858+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:26:47.857+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:26:47.860+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:26:48.022+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:26:48.022+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:26:48.034+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:26:48.034+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:26:48.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.367 seconds
[2025-01-14T21:27:18.140+0000] {processor.py:186} INFO - Started process (PID=503) to work on /opt/airflow/dags/test.py
[2025-01-14T21:27:18.141+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:27:18.144+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:27:18.143+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:27:18.476+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:27:18.475+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:27:18.478+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:27:18.497+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:27:18.496+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:27:18.509+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:27:18.508+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:27:18.523+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.389 seconds
[2025-01-14T21:27:48.610+0000] {processor.py:186} INFO - Started process (PID=513) to work on /opt/airflow/dags/test.py
[2025-01-14T21:27:48.610+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:27:48.613+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:27:48.612+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:27:48.936+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:27:48.935+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:27:48.938+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:27:48.957+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:27:48.957+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:27:48.969+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:27:48.968+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:27:48.986+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.382 seconds
[2025-01-14T21:28:19.290+0000] {processor.py:186} INFO - Started process (PID=522) to work on /opt/airflow/dags/test.py
[2025-01-14T21:28:19.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:28:19.293+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:28:19.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:28:19.463+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:28:19.462+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:28:19.465+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:28:19.493+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:28:19.492+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:28:19.511+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:28:19.511+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:28:19.529+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.245 seconds
[2025-01-14T21:28:49.764+0000] {processor.py:186} INFO - Started process (PID=533) to work on /opt/airflow/dags/test.py
[2025-01-14T21:28:49.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:28:49.767+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:28:49.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:28:49.933+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:28:49.932+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:28:49.936+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:28:49.966+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:28:49.965+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:28:49.983+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:28:49.983+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:28:50.001+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.243 seconds
[2025-01-14T21:29:20.181+0000] {processor.py:186} INFO - Started process (PID=543) to work on /opt/airflow/dags/test.py
[2025-01-14T21:29:20.183+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:29:20.185+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:29:20.185+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:29:20.361+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:29:20.360+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:29:20.364+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:29:20.389+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:29:20.389+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:29:20.403+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:29:20.403+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:29:20.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.246 seconds
[2025-01-14T21:29:50.813+0000] {processor.py:186} INFO - Started process (PID=557) to work on /opt/airflow/dags/test.py
[2025-01-14T21:29:50.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:29:50.817+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:29:50.816+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:29:50.986+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:29:50.985+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:29:50.989+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:29:51.018+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:29:51.017+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:29:51.033+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:29:51.033+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:29:51.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.243 seconds
[2025-01-14T21:30:21.271+0000] {processor.py:186} INFO - Started process (PID=567) to work on /opt/airflow/dags/test.py
[2025-01-14T21:30:21.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:30:21.275+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:30:21.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:30:21.592+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:30:21.591+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:30:21.595+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:30:21.623+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:30:21.623+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:30:21.641+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:30:21.641+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:30:21.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.401 seconds
[2025-01-14T21:30:51.849+0000] {processor.py:186} INFO - Started process (PID=577) to work on /opt/airflow/dags/test.py
[2025-01-14T21:30:51.849+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:30:51.851+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:30:51.851+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:30:52.032+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:30:52.031+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:30:52.035+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:30:52.064+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:30:52.064+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:30:52.083+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:30:52.083+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:30:52.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.259 seconds
[2025-01-14T21:31:22.323+0000] {processor.py:186} INFO - Started process (PID=587) to work on /opt/airflow/dags/test.py
[2025-01-14T21:31:22.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:31:22.326+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:31:22.326+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:31:22.500+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:31:22.499+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:31:22.503+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:31:22.530+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:31:22.530+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:31:22.549+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:31:22.548+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:31:22.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.251 seconds
[2025-01-14T21:31:52.841+0000] {processor.py:186} INFO - Started process (PID=599) to work on /opt/airflow/dags/test.py
[2025-01-14T21:31:52.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:31:52.844+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:31:52.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:31:53.019+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:31:53.018+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:31:53.022+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:31:53.047+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:31:53.047+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:31:53.060+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:31:53.060+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:31:53.078+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.243 seconds
[2025-01-14T21:32:23.258+0000] {processor.py:186} INFO - Started process (PID=609) to work on /opt/airflow/dags/test.py
[2025-01-14T21:32:23.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:32:23.261+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:32:23.261+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:32:23.432+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:32:23.431+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:32:23.435+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:32:23.459+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:32:23.458+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:32:23.473+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:32:23.473+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:32:23.490+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.238 seconds
[2025-01-14T21:32:53.723+0000] {processor.py:186} INFO - Started process (PID=619) to work on /opt/airflow/dags/test.py
[2025-01-14T21:32:53.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:32:53.727+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:32:53.726+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:32:54.018+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:32:54.017+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:32:54.021+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:32:54.046+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:32:54.045+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:32:54.059+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:32:54.058+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:32:54.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.361 seconds
[2025-01-14T21:33:24.215+0000] {processor.py:186} INFO - Started process (PID=629) to work on /opt/airflow/dags/test.py
[2025-01-14T21:33:24.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:33:24.219+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:33:24.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:33:24.390+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:33:24.389+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:33:24.392+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:33:24.420+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:33:24.419+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:33:24.433+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:33:24.433+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:33:24.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.243 seconds
[2025-01-14T21:33:54.627+0000] {processor.py:186} INFO - Started process (PID=639) to work on /opt/airflow/dags/test.py
[2025-01-14T21:33:54.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:33:54.631+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:33:54.630+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:33:54.803+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:33:54.801+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:33:54.805+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:33:54.827+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:33:54.827+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:33:54.842+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:33:54.842+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:33:54.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.238 seconds
[2025-01-14T21:34:25.076+0000] {processor.py:186} INFO - Started process (PID=649) to work on /opt/airflow/dags/test.py
[2025-01-14T21:34:25.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:34:25.079+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:34:25.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:34:25.268+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:34:25.267+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:34:25.271+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:34:25.301+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:34:25.301+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:34:25.319+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:34:25.318+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:34:25.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.272 seconds
[2025-01-14T21:34:55.544+0000] {processor.py:186} INFO - Started process (PID=664) to work on /opt/airflow/dags/test.py
[2025-01-14T21:34:55.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-14T21:34:55.546+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:34:55.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-14T21:34:55.718+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:34:55.717+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-14T21:34:55.721+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-14T21:34:55.743+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:34:55.743+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T21:34:55.756+0000] {logging_mixin.py:190} INFO - [2025-01-14T21:34:55.756+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-14T21:34:55.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.237 seconds
